# api_pdf_generator.py — NexTest API Test Report Generator
# Dedicated PDF generator for API tests (Postman / Newman CLI / Pytest)
# Compatible with api_generator.py + api_runner.py output format

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor, white, black
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable, KeepTogether
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from io import BytesIO
import json
from datetime import datetime

# ── Color Palette ──────────────────────────────────────────────────────────────
NAVY        = HexColor('#0a0f1e')
GOLD        = HexColor('#c9a227')
GREEN       = HexColor('#10b981')
GREEN_BG    = HexColor('#d1fae5')
RED         = HexColor('#ef4444')
RED_BG      = HexColor('#fee2e2')
ORANGE      = HexColor('#f59e0b')
ORANGE_BG   = HexColor('#fef3c7')
BLUE        = HexColor('#3b82f6')
BLUE_BG     = HexColor('#dbeafe')
LIGHT_BG    = HexColor('#f8fafc')
BORDER      = HexColor('#e2e8f0')
BORDER_DARK = HexColor('#cbd5e1')
MUTED       = HexColor('#94a3b8')
DARK_TEXT   = HexColor('#1e293b')
WHITE       = white

PURPLE      = HexColor('#8b5cf6')
PURPLE_BG   = HexColor('#ede9fe')
TEAL        = HexColor('#0d9488')
TEAL_BG     = HexColor('#ccfbf1')
INDIGO      = HexColor('#4f46e5')
INDIGO_BG   = HexColor('#e0e7ff')

# Framework colors
POSTMAN_COLOR  = HexColor('#FF6C37')
POSTMAN_BG     = HexColor('#fff3ef')
PYTEST_COLOR   = HexColor('#3776AB')
PYTEST_BG      = HexColor('#e8f0f8')
NEWMAN_COLOR   = HexColor('#FF6C37')
NEWMAN_BG      = HexColor('#fff3ef')

# Method colors
METHOD_COLORS = {
    'GET':    ('#10b981', '#d1fae5'),
    'POST':   ('#3b82f6', '#dbeafe'),
    'PUT':    ('#f59e0b', '#fef3c7'),
    'DELETE': ('#ef4444', '#fee2e2'),
    'PATCH':  ('#8b5cf6', '#ede9fe'),
}

# Priority colors
PRIORITY_COLORS = {
    'high':     '#ef4444',
    'medium':   '#f59e0b',
    'low':      '#10b981',
    'critical': '#dc2626',
}

# Severity colors for LLaMA analysis
SEVERITY_COLORS = {
    'critical': ('#ef4444', '#fee2e2'),
    'high':     ('#f97316', '#fff7ed'),
    'medium':   ('#f59e0b', '#fef3c7'),
    'low':      ('#10b981', '#d1fae5'),
}

# Category colors
CATEGORY_COLORS = {
    'auth':          '#6366f1',
    'dossiers':      '#10b981',
    'commissions':   '#f59e0b',
    'users':         '#3b82f6',
    'roles':         '#8b5cf6',
    'notifications': '#0d9488',
    'meetings':      '#ec4899',
    'inspections':   '#f97316',
    'promoteurs':    '#14b8a6',
    'regions':       '#64748b',
    'auditing':      '#dc2626',
    'dashboard':     '#c9a227',
    'api':           '#4f46e5',
}


# ── Page Chrome ────────────────────────────────────────────────────────────────

def on_page_api(canvas, doc):
    W, H = A4
    canvas.saveState()
    # Top bar
    canvas.setFillColor(NAVY)
    canvas.rect(0, H - 52*mm, W, 52*mm, fill=1, stroke=0)
    canvas.setFillColor(POSTMAN_COLOR)
    canvas.rect(0, H - 54*mm, W, 2*mm, fill=1, stroke=0)
    # Left accent
    canvas.setFillColor(POSTMAN_COLOR)
    canvas.rect(0, 0, 3, H - 54*mm, fill=1, stroke=0)
    # Footer
    canvas.setFillColor(LIGHT_BG)
    canvas.rect(0, 0, W, 14*mm, fill=1, stroke=0)
    canvas.setFillColor(BORDER)
    canvas.rect(0, 14*mm, W, 0.5, fill=1, stroke=0)
    canvas.setFont('Helvetica', 7.5)
    canvas.setFillColor(MUTED)
    canvas.drawString(20*mm, 5*mm, 'Generated by NexTest — AI-Powered API Test Automation')
    canvas.drawRightString(W - 20*mm, 5*mm, f'Page {doc.page}  •  {datetime.now().strftime("%Y-%m-%d")}')
    canvas.restoreState()


# ── Shared Helpers ─────────────────────────────────────────────────────────────

def section_header(emoji, text, color=None):
    accent = color or POSTMAN_COLOR
    data = [[Paragraph(
        f'{emoji}  {text}',
        ParagraphStyle('SH', fontSize=11, fontName='Helvetica-Bold',
                       textColor=DARK_TEXT, leading=14))]]
    tbl = Table(data, colWidths=[168*mm])
    tbl.setStyle(TableStyle([
        ('LINEBELOW',     (0,0), (-1,-1), 1.5, accent),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ('TOPPADDING',    (0,0), (-1,-1), 0),
    ]))
    return tbl


def stat_card(value, label, val_color, bg_color):
    inner = [[Paragraph(
        f'<font color="{val_color}"><b>{value}</b></font><br/>'
        f'<font color="#94a3b8" size="7"><b>{label}</b></font>',
        ParagraphStyle('SC', fontSize=18, fontName='Helvetica-Bold',
                       alignment=TA_CENTER, leading=26))]]
    t = Table(inner, colWidths=[30*mm])
    t.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (-1,-1), bg_color),
        ('BOX',           (0,0), (-1,-1), 1, BORDER_DARK),
        ('TOPPADDING',    (0,0), (-1,-1), 12),
        ('BOTTOMPADDING', (0,0), (-1,-1), 12),
        ('ALIGN',         (0,0), (-1,-1), 'CENTER'),
    ]))
    return t


def method_badge(method: str) -> str:
    color, _ = METHOD_COLORS.get(method.upper(), ('#64748b', '#f8fafc'))
    return f'<font color="{color}"><b>{method.upper()}</b></font>'


def _fw_display(framework: str) -> tuple:
    """Returns (display_name, color_hex_str, bg_color, short_label)"""
    fw = framework.lower() if framework else ''
    if 'postman' in fw or 'newman' in fw:
        return 'Postman / Newman CLI', '#FF6C37', POSTMAN_BG, 'Po'
    elif 'pytest' in fw:
        return 'Pytest + requests', '#3776AB', PYTEST_BG, 'Py'
    else:
        return framework, '#FF6C37', POSTMAN_BG, (fw[:2].upper() if fw else 'AP')


# ── Section 1 : API Test Plan ──────────────────────────────────────────────────

def build_api_test_plan(elements, test_cases: list, base_url: str,
                         framework: str, domains: list):
    elements.append(section_header('📋', 'API Test Plan', INDIGO))
    elements.append(Spacer(1, 4))
    elements.append(Paragraph(
        '<font color="#64748b" size="7.5"><i>'
        'Overview of all API endpoints scheduled for execution — '
        'grouped by domain/category with method, expected status, and priority.'
        '</i></font>',
        ParagraphStyle('TPInfo', fontSize=7.5, fontName='Helvetica', leading=10)))
    elements.append(Spacer(1, 8))

    fw_name, fw_color, fw_bg, fw_short = _fw_display(framework)

    # Summary meta table
    domains_str = ', '.join(d.upper() for d in (domains or [])) or 'AUTO-DETECTED'
    meta_rows = [
        [_lbl('Base URL'),   _val(base_url)],
        [_lbl('Framework'),  Paragraph(
            f'<font color="{fw_color}"><b>{fw_name}</b></font>',
            ParagraphStyle('FWV', fontSize=8.5, fontName='Helvetica', leading=12))],
        [_lbl('Domains'),    _val(domains_str)],
        [_lbl('Total Tests'),_val(f'{len(test_cases)} test case(s) planned')],
    ]
    meta_tbl = Table(meta_rows, colWidths=[32*mm, 136*mm])
    meta_tbl.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (0,-1), LIGHT_BG),
        ('ROWBACKGROUNDS',(0,0), (-1,-1), [WHITE, LIGHT_BG]),
        ('PADDING',       (0,0), (-1,-1), 7),
        ('LINEBELOW',     (0,0), (-1,-2), 0.4, BORDER),
        ('BOX',           (0,0), (-1,-1), 0.8, BORDER_DARK),
        ('VALIGN',        (0,0), (-1,-1), 'MIDDLE'),
        ('LEFTPADDING',   (0,0), (0,-1), 10),
    ]))
    elements.append(meta_tbl)
    elements.append(Spacer(1, 14))

    # Group test cases by category/domain
    grouped = {}
    for tc in test_cases:
        cat = tc.get('category', 'api')
        grouped.setdefault(cat, []).append(tc)

    for cat, tcs in grouped.items():
        cat_color = CATEGORY_COLORS.get(cat, '#4f46e5')
        cat_pass  = sum(1 for t in tcs if t.get('status') == 'pass')
        cat_fail  = sum(1 for t in tcs if t.get('status') == 'fail')
        cat_total = len(tcs)
        cat_rate  = round(cat_pass / cat_total * 100) if cat_total else 0
        rc = '#10b981' if cat_rate >= 80 else '#f59e0b' if cat_rate >= 50 else '#ef4444'

        # Category header row
        cat_hdr = Table([[
            Paragraph(
                f'<font color="{cat_color}"><b>◆  {cat.upper()}</b></font>'
                f'  <font color="#94a3b8" size="7">({cat_total} tests)</font>'
                f'  <font color="{rc}" size="7"><b>{cat_rate}% pass</b></font>',
                ParagraphStyle('CH', fontSize=9, fontName='Helvetica-Bold', leading=12))
        ]], colWidths=[168*mm])
        cat_hdr.setStyle(TableStyle([
            ('BACKGROUND',    (0,0), (-1,-1), HexColor(cat_color + '15') if len(cat_color) == 7 else INDIGO_BG),
            ('LEFTPADDING',   (0,0), (-1,-1), 10),
            ('TOPPADDING',    (0,0), (-1,-1), 6),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
            ('LINEBELOW',     (0,0), (-1,-1), 1, HexColor(cat_color)),
        ]))
        elements.append(cat_hdr)

        # Endpoint rows header
        hdr = [
            Paragraph('<font color="#ffffff"><b>#</b></font>',
                      ParagraphStyle('PH0', fontSize=7.5, fontName='Helvetica-Bold', alignment=TA_CENTER)),
            Paragraph('<font color="#ffffff"><b>Method</b></font>',
                      ParagraphStyle('PH1', fontSize=7.5, fontName='Helvetica-Bold', alignment=TA_CENTER)),
            Paragraph('<font color="#ffffff"><b>Test Name</b></font>',
                      ParagraphStyle('PH2', fontSize=7.5, fontName='Helvetica-Bold')),
            Paragraph('<font color="#ffffff"><b>Path</b></font>',
                      ParagraphStyle('PH3', fontSize=7.5, fontName='Helvetica-Bold')),
            Paragraph('<font color="#ffffff"><b>Expect</b></font>',
                      ParagraphStyle('PH4', fontSize=7.5, fontName='Helvetica-Bold', alignment=TA_CENTER)),
            Paragraph('<font color="#ffffff"><b>Priority</b></font>',
                      ParagraphStyle('PH5', fontSize=7.5, fontName='Helvetica-Bold', alignment=TA_CENTER)),
            Paragraph('<font color="#ffffff"><b>Auth</b></font>',
                      ParagraphStyle('PH6', fontSize=7.5, fontName='Helvetica-Bold', alignment=TA_CENTER)),
        ]
        rows = [hdr]

        for i, tc in enumerate(tcs):
            method = tc.get('method', 'GET').upper()
            mc, mbg = METHOD_COLORS.get(method, ('#64748b', '#f8fafc'))
            expect = tc.get('expect_status', 200)
            priority = tc.get('priority', 'medium')
            pri_color = PRIORITY_COLORS.get(priority, '#64748b')
            skip_auth = tc.get('skip_auth', False)
            path = tc.get('path', tc.get('url', ''))
            if len(path) > 50:
                path = path[:47] + '...'
            name = tc.get('name', '')
            is_edge = tc.get('is_edge_case', False)

            rows.append([
                Paragraph(f'<font color="#64748b"><b>{tc.get("id", i+1)}</b></font>',
                          ParagraphStyle('ID', fontSize=7.5, fontName='Helvetica-Bold', alignment=TA_CENTER)),
                Paragraph(f'<font color="{mc}"><b>{method}</b></font>',
                          ParagraphStyle('MT', fontSize=7.5, fontName='Helvetica-Bold', alignment=TA_CENTER)),
                Paragraph(
                    f'<font color="#1e293b" size="7.5"><b>{name[:45]}</b></font>'
                    + (f'<br/><font color="#8b5cf6" size="6"><b>EDGE CASE</b></font>' if is_edge else ''),
                    ParagraphStyle('NM', fontSize=7.5, fontName='Helvetica', leading=10)),
                Paragraph(f'<font color="#4f46e5" size="6.5">{path}</font>',
                          ParagraphStyle('PT', fontSize=6.5, fontName='Courier', leading=9)),
                Paragraph(_status_code_badge(expect),
                          ParagraphStyle('EX', fontSize=7.5, fontName='Helvetica-Bold', alignment=TA_CENTER)),
                Paragraph(f'<font color="{pri_color}"><b>{priority.upper()}</b></font>',
                          ParagraphStyle('PR', fontSize=7, fontName='Helvetica-Bold', alignment=TA_CENTER)),
                Paragraph(
                    '<font color="#94a3b8">NO AUTH</font>' if skip_auth
                    else '<font color="#10b981"><b>JWT ✓</b></font>',
                    ParagraphStyle('AU', fontSize=6.5, fontName='Helvetica', alignment=TA_CENTER)),
            ])

        tbl = Table(rows, colWidths=[8*mm, 16*mm, 48*mm, 48*mm, 16*mm, 18*mm, 14*mm], repeatRows=1)
        tbl.setStyle(TableStyle([
            ('BACKGROUND',    (0,0), (-1,0), NAVY),
            ('ROWBACKGROUNDS',(0,1), (-1,-1), [WHITE, HexColor('#f0f4ff')]),
            ('PADDING',       (0,0), (-1,-1), 6),
            ('LINEBELOW',     (0,0), (-1,-1), 0.4, BORDER),
            ('BOX',           (0,0), (-1,-1), 0.8, INDIGO),
            ('VALIGN',        (0,0), (-1,-1), 'TOP'),
            ('ALIGN',         (0,0), (0,-1), 'CENTER'),
            ('ALIGN',         (1,0), (1,-1), 'CENTER'),
            ('ALIGN',         (4,0), (4,-1), 'CENTER'),
            ('ALIGN',         (5,0), (5,-1), 'CENTER'),
            ('ALIGN',         (6,0), (6,-1), 'CENTER'),
        ]))
        elements.append(tbl)
        elements.append(Spacer(1, 10))

    elements.append(Spacer(1, 8))


# ── Section 2 : Test Summary ───────────────────────────────────────────────────

def build_api_stats_section(elements, execution_results: list):
    total      = len(execution_results)
    pass_count = sum(1 for r in execution_results if r.get('status') == 'pass')
    fail_count = sum(1 for r in execution_results if r.get('status') == 'fail')
    skip_count = sum(1 for r in execution_results if r.get('status') == 'skip')
    rate       = round(pass_count / total * 100) if total else 0
    rate_hex   = '#10b981' if rate >= 80 else '#f59e0b' if rate >= 50 else '#ef4444'
    rate_bg    = GREEN_BG  if rate >= 80 else ORANGE_BG  if rate >= 50 else RED_BG

    avg_duration = _avg_duration(execution_results)

    stats_data = [[
        stat_card(pass_count, 'PASSED',      '#10b981', GREEN_BG),
        stat_card(fail_count, 'FAILED',      '#ef4444', RED_BG),
        stat_card(skip_count, 'SKIPPED',     '#f59e0b', ORANGE_BG),
        stat_card(f'{rate}%', 'PASS RATE',   rate_hex,  rate_bg),
        stat_card(total,      'TOTAL',       '#3b82f6', BLUE_BG),
        stat_card(avg_duration, 'AVG TIME',  '#8b5cf6', PURPLE_BG),
    ]]
    outer = Table(stats_data, colWidths=[28*mm]*6)
    outer.setStyle(TableStyle([
        ('ALIGN',  (0,0), (-1,-1), 'CENTER'),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('PADDING',(0,0), (-1,-1), 2),
    ]))
    elements.append(outer)
    elements.append(Spacer(1, 14))

    # Pass rate bar
    bar_data = [[Paragraph(
        f'<font color="{rate_hex}" size="9"><b>Overall Pass Rate: {rate}%</b></font>  '
        f'<font color="#94a3b8" size="8">({pass_count} passed / {fail_count} failed / {skip_count} skipped / {total} total)</font>',
        ParagraphStyle('RB', fontSize=9, fontName='Helvetica', leading=12))]]
    bar_outer = Table(bar_data, colWidths=[168*mm])
    bar_outer.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (-1,-1), rate_bg),
        ('BOX',           (0,0), (-1,-1), 1, HexColor(rate_hex)),
        ('LEFTPADDING',   (0,0), (-1,-1), 12),
        ('TOPPADDING',    (0,0), (-1,-1), 8),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
    ]))
    elements.append(bar_outer)
    elements.append(Spacer(1, 16))


# ── Section 3 : Execution Results ─────────────────────────────────────────────

def build_api_execution_results(elements, execution_results: list):
    elements.append(section_header('🚀', 'Execution Results', TEAL))
    elements.append(Spacer(1, 4))
    elements.append(Paragraph(
        '<font color="#64748b" size="7.5"><i>'
        'Detailed results for each API test — actual HTTP status, response time, '
        'field assertions, and AI analysis inline.'
        '</i></font>',
        ParagraphStyle('ERInfo', fontSize=7.5, fontName='Helvetica', leading=10)))
    elements.append(Spacer(1, 8))

    hdr = [
        Paragraph('<font color="#ffffff"><b>#</b></font>',
                  ParagraphStyle('EH0', fontSize=7.5, fontName='Helvetica-Bold', alignment=TA_CENTER)),
        Paragraph('<font color="#ffffff"><b>Test Name</b></font>',
                  ParagraphStyle('EH1', fontSize=7.5, fontName='Helvetica-Bold')),
        Paragraph('<font color="#ffffff"><b>Method · URL</b></font>',
                  ParagraphStyle('EH2', fontSize=7.5, fontName='Helvetica-Bold')),
        Paragraph('<font color="#ffffff"><b>Exp.</b></font>',
                  ParagraphStyle('EH3', fontSize=7.5, fontName='Helvetica-Bold', alignment=TA_CENTER)),
        Paragraph('<font color="#ffffff"><b>Got</b></font>',
                  ParagraphStyle('EH4', fontSize=7.5, fontName='Helvetica-Bold', alignment=TA_CENTER)),
        Paragraph('<font color="#ffffff"><b>Status</b></font>',
                  ParagraphStyle('EH5', fontSize=7.5, fontName='Helvetica-Bold', alignment=TA_CENTER)),
        Paragraph('<font color="#ffffff"><b>Time</b></font>',
                  ParagraphStyle('EH6', fontSize=7.5, fontName='Helvetica-Bold', alignment=TA_CENTER)),
        Paragraph('<font color="#ffffff"><b>Result / Assertion</b></font>',
                  ParagraphStyle('EH7', fontSize=7.5, fontName='Helvetica-Bold')),
    ]
    rows = [hdr]
    row_styles = []

    for i, r in enumerate(execution_results):
        status   = r.get('status', 'skip')
        method   = r.get('method', 'GET').upper()
        url      = r.get('url', '')
        expected = r.get('expected_status', '—')
        actual   = r.get('http_status', '—')
        duration = r.get('duration', '—')
        name     = r.get('name', '')
        reason   = r.get('reason') or r.get('error') or r.get('reason_pass') or ''
        priority = r.get('priority', 'medium')
        category = r.get('category', 'api')

        mc, _  = METHOD_COLORS.get(method, ('#64748b', '#f8fafc'))
        sc, sb = _status_result_colors(status)
        pri_c  = PRIORITY_COLORS.get(priority, '#64748b')
        cat_c  = CATEGORY_COLORS.get(category, '#4f46e5')

        # URL short
        url_short = url
        base_strip = url_short
        for proto in ['https://', 'http://']:
            base_strip = base_strip.replace(proto, '')
        parts = base_strip.split('/', 1)
        path_part = '/' + parts[1] if len(parts) > 1 else base_strip
        if len(path_part) > 48:
            path_part = path_part[:45] + '...'

        # Reason short
        reason_short = str(reason)[:80] + ('...' if len(str(reason)) > 80 else '')

        # Assertions detail
        assertions_detail = r.get('assertions_detail', [])
        passed_a = sum(1 for a in assertions_detail if a.get('passed'))
        total_a  = len(assertions_detail)
        assertion_summary = ''
        if total_a > 0:
            ac = '#10b981' if passed_a == total_a else '#ef4444'
            assertion_summary = f'<br/><font color="{ac}" size="6.5">Assertions: {passed_a}/{total_a} passed</font>'

        result_cell = Paragraph(
            f'<font color="{sc}" size="7">{reason_short}</font>{assertion_summary}',
            ParagraphStyle('RC', fontSize=7, fontName='Helvetica', leading=9.5))

        rows.append([
            Paragraph(f'<font color="#64748b"><b>{i+1}</b></font>',
                      ParagraphStyle('EID', fontSize=7.5, fontName='Helvetica-Bold', alignment=TA_CENTER)),
            Paragraph(
                f'<font color="#1e293b" size="7.5"><b>{name[:40]}</b></font><br/>'
                f'<font color="{cat_c}" size="6"><b>{category.upper()}</b></font>'
                f'  <font color="{pri_c}" size="6"><b>{priority.upper()}</b></font>',
                ParagraphStyle('EN', fontSize=7.5, fontName='Helvetica', leading=10)),
            Paragraph(
                f'<font color="{mc}"><b>{method}</b></font>  '
                f'<font color="#4f46e5" size="6.5">{path_part}</font>',
                ParagraphStyle('EU', fontSize=6.5, fontName='Courier', leading=9.5)),
            Paragraph(_status_code_badge(expected),
                      ParagraphStyle('EEX', fontSize=7.5, fontName='Helvetica-Bold', alignment=TA_CENTER)),
            Paragraph(_status_code_badge(actual),
                      ParagraphStyle('EAC', fontSize=7.5, fontName='Helvetica-Bold', alignment=TA_CENTER)),
            Paragraph(f'<font color="{sc}"><b>{status.upper()}</b></font>',
                      ParagraphStyle('EST', fontSize=7.5, fontName='Helvetica-Bold', alignment=TA_CENTER)),
            Paragraph(f'<font color="#64748b" size="7">{duration}</font>',
                      ParagraphStyle('ETM', fontSize=7, fontName='Helvetica', alignment=TA_CENTER)),
            result_cell,
        ])
        row_styles.append(('BACKGROUND', (0, i+1), (-1, i+1), HexColor(sb)))

    tbl = Table(rows,
                colWidths=[7*mm, 36*mm, 38*mm, 12*mm, 12*mm, 14*mm, 14*mm, 35*mm],
                repeatRows=1)
    tbl.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (-1,0), NAVY),
        ('PADDING',       (0,0), (-1,-1), 6),
        ('LINEBELOW',     (0,0), (-1,-1), 0.4, BORDER),
        ('BOX',           (0,0), (-1,-1), 0.8, TEAL),
        ('VALIGN',        (0,0), (-1,-1), 'TOP'),
        ('ALIGN',         (0,0), (0,-1), 'CENTER'),
        ('ALIGN',         (3,0), (3,-1), 'CENTER'),
        ('ALIGN',         (4,0), (4,-1), 'CENTER'),
        ('ALIGN',         (5,0), (5,-1), 'CENTER'),
        ('ALIGN',         (6,0), (6,-1), 'CENTER'),
        ('LINEBEFORE',    (3,1), (3,-1), 1, BORDER_DARK),
        ('LINEBEFORE',    (7,1), (7,-1), 1, BORDER),
    ] + row_styles))
    elements.append(tbl)
    elements.append(Spacer(1, 16))


# ── Section 4 : Assertions Detail ─────────────────────────────────────────────

def build_api_assertions_detail(elements, execution_results: list):
    # Only include tests that have assertions_detail
    relevant = [r for r in execution_results if r.get('assertions_detail')]
    if not relevant:
        return

    elements.append(section_header('🔬', 'Assertions Detail', PURPLE))
    elements.append(Spacer(1, 4))
    elements.append(Paragraph(
        '<font color="#64748b" size="7.5"><i>'
        'Per-assertion breakdown for each test — '
        'generated by Groq LLaMA3 and validated against real API responses.'
        '</i></font>',
        ParagraphStyle('ADInfo', fontSize=7.5, fontName='Helvetica', leading=10)))
    elements.append(Spacer(1, 8))

    for r in relevant:
        name     = r.get('name', '')
        status   = r.get('status', 'skip')
        method   = r.get('method', 'GET').upper()
        mc, _    = METHOD_COLORS.get(method, ('#64748b', '#f8fafc'))
        sc, sb   = _status_result_colors(status)
        assertions = r.get('assertions_detail', [])

        # Test header
        test_hdr = Table([[Paragraph(
            f'<font color="{mc}"><b>{method}</b></font>  '
            f'<font color="#1e293b"><b>{name[:60]}</b></font>  '
            f'<font color="{sc}"><b>→ {status.upper()}</b></font>',
            ParagraphStyle('AH', fontSize=8.5, fontName='Helvetica-Bold', leading=12))
        ]], colWidths=[168*mm])
        test_hdr.setStyle(TableStyle([
            ('BACKGROUND',    (0,0), (-1,-1), HexColor(sb)),
            ('LEFTPADDING',   (0,0), (-1,-1), 10),
            ('TOPPADDING',    (0,0), (-1,-1), 6),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
            ('BOX',           (0,0), (-1,-1), 0.8, HexColor(sc)),
        ]))
        elements.append(test_hdr)

        if not assertions:
            elements.append(Spacer(1, 4))
            continue

        # Assertions table
        a_hdr = [
            Paragraph('<font color="#ffffff"><b>Type</b></font>',
                      ParagraphStyle('AHT', fontSize=7, fontName='Helvetica-Bold')),
            Paragraph('<font color="#ffffff"><b>Description</b></font>',
                      ParagraphStyle('AHD', fontSize=7, fontName='Helvetica-Bold')),
            Paragraph('<font color="#ffffff"><b>Expected</b></font>',
                      ParagraphStyle('AHE', fontSize=7, fontName='Helvetica-Bold')),
            Paragraph('<font color="#ffffff"><b>Actual</b></font>',
                      ParagraphStyle('AHA', fontSize=7, fontName='Helvetica-Bold')),
            Paragraph('<font color="#ffffff"><b>Result</b></font>',
                      ParagraphStyle('AHR', fontSize=7, fontName='Helvetica-Bold', alignment=TA_CENTER)),
            Paragraph('<font color="#ffffff"><b>Critical</b></font>',
                      ParagraphStyle('AHC', fontSize=7, fontName='Helvetica-Bold', alignment=TA_CENTER)),
        ]
        a_rows = [a_hdr]
        a_styles = []

        for j, a in enumerate(assertions):
            passed   = a.get('passed', False)
            critical = a.get('critical', False)
            atype    = a.get('type', '')
            adesc    = a.get('description', '')
            aexp     = str(a.get('expected', ''))[:40]
            aact     = str(a.get('actual', '—'))[:40]
            aerr     = a.get('error', '')
            ac       = '#10b981' if passed else '#ef4444'
            abg      = HexColor('#f0fdf4') if passed else HexColor('#fef2f2')

            a_rows.append([
                Paragraph(f'<font color="#6366f1" size="6.5"><b>{atype}</b></font>',
                          ParagraphStyle('AT', fontSize=6.5, fontName='Helvetica-Bold')),
                Paragraph(f'<font color="#475569" size="6.5">{adesc[:55]}</font>',
                          ParagraphStyle('AD', fontSize=6.5, fontName='Helvetica', leading=9)),
                Paragraph(f'<font color="#1e293b" size="6.5">{aexp}</font>',
                          ParagraphStyle('AE', fontSize=6.5, fontName='Courier', leading=9)),
                Paragraph(
                    f'<font color="{ac}" size="6.5">{aact}</font>'
                    + (f'<br/><font color="#ef4444" size="6">{aerr[:30]}</font>' if aerr else ''),
                    ParagraphStyle('AA', fontSize=6.5, fontName='Courier', leading=9)),
                Paragraph(
                    f'<font color="{ac}"><b>{"✓ PASS" if passed else "✗ FAIL"}</b></font>',
                    ParagraphStyle('AR', fontSize=6.5, fontName='Helvetica-Bold', alignment=TA_CENTER)),
                Paragraph(
                    '<font color="#ef4444"><b>YES</b></font>' if critical
                    else '<font color="#94a3b8">—</font>',
                    ParagraphStyle('AC', fontSize=6.5, fontName='Helvetica-Bold', alignment=TA_CENTER)),
            ])
            a_styles.append(('BACKGROUND', (0, j+1), (-1, j+1), abg))

        a_tbl = Table(a_rows, colWidths=[22*mm, 52*mm, 30*mm, 30*mm, 18*mm, 16*mm],
                      repeatRows=1)
        a_tbl.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), NAVY),
            ('PADDING',    (0,0), (-1,-1), 5),
            ('LINEBELOW',  (0,0), (-1,-1), 0.3, BORDER),
            ('BOX',        (0,0), (-1,-1), 0.8, PURPLE),
            ('VALIGN',     (0,0), (-1,-1), 'TOP'),
            ('ALIGN',      (4,0), (5,-1), 'CENTER'),
        ] + a_styles))
        elements.append(a_tbl)
        elements.append(Spacer(1, 8))

    elements.append(Spacer(1, 8))


# ── Section 5 : LLaMA Analysis ────────────────────────────────────────────────

def build_api_llama_analysis(elements, execution_results: list):
    relevant = [r for r in execution_results if r.get('ai_analysis')]
    if not relevant:
        return

    elements.append(section_header('🤖', 'LLaMA AI Analysis', INDIGO))
    elements.append(Spacer(1, 4))
    elements.append(Paragraph(
        '<font color="#64748b" size="7.5"><i>'
        'Root cause analysis and fix recommendations generated by Groq LLaMA3 '
        'for every test — pass, fail, and skip alike.'
        '</i></font>',
        ParagraphStyle('LAInfo', fontSize=7.5, fontName='Helvetica', leading=10)))
    elements.append(Spacer(1, 8))

    hdr = [
        Paragraph('<font color="#ffffff"><b>#</b></font>',
                  ParagraphStyle('LH0', fontSize=7.5, fontName='Helvetica-Bold', alignment=TA_CENTER)),
        Paragraph('<font color="#ffffff"><b>Test Name</b></font>',
                  ParagraphStyle('LH1', fontSize=7.5, fontName='Helvetica-Bold')),
        Paragraph('<font color="#ffffff"><b>Status</b></font>',
                  ParagraphStyle('LH2', fontSize=7.5, fontName='Helvetica-Bold', alignment=TA_CENTER)),
        Paragraph('<font color="#ffffff"><b>Severity</b></font>',
                  ParagraphStyle('LH3', fontSize=7.5, fontName='Helvetica-Bold', alignment=TA_CENTER)),
        Paragraph('<font color="#ffffff"><b>Root Cause</b></font>',
                  ParagraphStyle('LH4', fontSize=7.5, fontName='Helvetica-Bold')),
        Paragraph('<font color="#ffffff"><b>Fix / Recommendation</b></font>',
                  ParagraphStyle('LH5', fontSize=7.5, fontName='Helvetica-Bold')),
    ]
    rows = [hdr]
    row_styles = []

    for i, r in enumerate(relevant):
        ai     = r.get('ai_analysis', {})
        status = r.get('status', 'skip')
        sev    = ai.get('severity', 'medium')
        rc_txt = ai.get('root_cause', '')[:100]
        fix    = ai.get('fix', '')[:100]
        name   = r.get('name', '')

        sc, sb      = _status_result_colors(status)
        sevc, sevbg = SEVERITY_COLORS.get(sev, ('#f59e0b', '#fef3c7'))

        rows.append([
            Paragraph(f'<font color="#64748b"><b>{i+1}</b></font>',
                      ParagraphStyle('LID', fontSize=7.5, fontName='Helvetica-Bold', alignment=TA_CENTER)),
            Paragraph(f'<font color="#1e293b" size="7.5"><b>{name[:45]}</b></font>',
                      ParagraphStyle('LN', fontSize=7.5, fontName='Helvetica', leading=10)),
            Paragraph(f'<font color="{sc}"><b>{status.upper()}</b></font>',
                      ParagraphStyle('LS', fontSize=7.5, fontName='Helvetica-Bold', alignment=TA_CENTER)),
            Paragraph(f'<font color="{sevc}"><b>{sev.upper()}</b></font>',
                      ParagraphStyle('LSV', fontSize=7, fontName='Helvetica-Bold', alignment=TA_CENTER)),
            Paragraph(f'<font color="#475569" size="7">{rc_txt}</font>',
                      ParagraphStyle('LRC', fontSize=7, fontName='Helvetica', leading=9.5)),
            Paragraph(
                f'<font color="#10b981" size="7"><b>→ </b></font>'
                f'<font color="#475569" size="7">{fix}</font>',
                ParagraphStyle('LFX', fontSize=7, fontName='Helvetica', leading=9.5)),
        ])
        row_styles.append(('BACKGROUND', (0, i+1), (-1, i+1), HexColor(sevbg)))

    tbl = Table(rows, colWidths=[7*mm, 40*mm, 16*mm, 18*mm, 48*mm, 39*mm], repeatRows=1)
    tbl.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (-1,0), NAVY),
        ('PADDING',       (0,0), (-1,-1), 6),
        ('LINEBELOW',     (0,0), (-1,-1), 0.4, BORDER),
        ('BOX',           (0,0), (-1,-1), 0.8, INDIGO),
        ('VALIGN',        (0,0), (-1,-1), 'TOP'),
        ('ALIGN',         (0,0), (0,-1), 'CENTER'),
        ('ALIGN',         (2,0), (3,-1), 'CENTER'),
        ('LINEBEFORE',    (4,1), (4,-1), 1, BORDER),
        ('LINEBEFORE',    (5,1), (5,-1), 1, BORDER),
    ] + row_styles))
    elements.append(tbl)
    elements.append(Spacer(1, 16))


# ── Section 6 : Verdict Summary ───────────────────────────────────────────────

def build_api_verdict_summary(elements, execution_results: list, framework: str):
    elements.append(section_header('🏁', 'Execution Verdict Summary', GOLD))
    elements.append(Spacer(1, 6))

    # Group by category
    cat_map = {}
    for r in execution_results:
        cat = r.get('category', 'api')
        cat_map.setdefault(cat, {'pass': 0, 'fail': 0, 'skip': 0})
        cat_map[cat][r.get('status', 'skip')] = cat_map[cat].get(r.get('status', 'skip'), 0) + 1

    hdr = [
        Paragraph('<font color="#ffffff"><b>Domain / Category</b></font>',
                  ParagraphStyle('VH1', fontSize=8, fontName='Helvetica-Bold')),
        Paragraph('<font color="#ffffff"><b>Verdict</b></font>',
                  ParagraphStyle('VH2', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
        Paragraph('<font color="#ffffff"><b>Pass</b></font>',
                  ParagraphStyle('VH3', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
        Paragraph('<font color="#ffffff"><b>Fail</b></font>',
                  ParagraphStyle('VH4', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
        Paragraph('<font color="#ffffff"><b>Skip</b></font>',
                  ParagraphStyle('VH5', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
        Paragraph('<font color="#ffffff"><b>Interpretation</b></font>',
                  ParagraphStyle('VH6', fontSize=8, fontName='Helvetica-Bold')),
    ]
    rows = [hdr]
    row_styles = []

    for cat, counts in cat_map.items():
        cat_color = CATEGORY_COLORS.get(cat, '#4f46e5')
        total_c   = counts['pass'] + counts['fail'] + counts['skip']
        rate_c    = round(counts['pass'] / total_c * 100) if total_c else 0

        if counts['fail'] > 0:
            vt, vc, vbg = 'FAIL', '#ef4444', HexColor('#fef2f2')
            interp = f'{counts["fail"]} endpoint(s) returned unexpected status — check API logs'
        elif counts['pass'] > 0:
            vt, vc, vbg = 'PASS', '#10b981', HexColor('#f0fdf4')
            interp = f'All {cat} endpoints responded correctly — {rate_c}% pass rate'
        else:
            vt, vc, vbg = 'SKIP', '#f59e0b', HexColor('#fffbeb')
            interp = 'No tests executed for this domain'

        rows.append([
            Paragraph(
                f'<font color="{cat_color}"><b>{cat.upper()}</b></font>  '
                f'<font color="#94a3b8" size="6.5">({total_c} tests)</font>',
                ParagraphStyle('VA', fontSize=8, fontName='Helvetica-Bold', leading=11)),
            Paragraph(f'<font color="{vc}"><b>{vt}</b></font>',
                      ParagraphStyle('VV', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
            Paragraph(f'<font color="#10b981"><b>{counts["pass"]}</b></font>',
                      ParagraphStyle('VP', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
            Paragraph(f'<font color="#ef4444"><b>{counts["fail"]}</b></font>',
                      ParagraphStyle('VF', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
            Paragraph(f'<font color="#f59e0b"><b>{counts["skip"]}</b></font>',
                      ParagraphStyle('VS', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
            Paragraph(f'<font color="#475569" size="7.5">{interp}</font>',
                      ParagraphStyle('VI', fontSize=7.5, fontName='Helvetica', leading=10)),
        ])
        ri = len(rows) - 1
        row_styles.append(('BACKGROUND', (0, ri), (-1, ri), vbg))

    tbl = Table(rows, colWidths=[36*mm, 18*mm, 14*mm, 14*mm, 14*mm, 72*mm], repeatRows=1)
    tbl.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (-1,0), NAVY),
        ('PADDING',       (0,0), (-1,-1), 7),
        ('LINEBELOW',     (0,0), (-1,-1), 0.4, BORDER),
        ('BOX',           (0,0), (-1,-1), 0.8, GOLD),
        ('VALIGN',        (0,0), (-1,-1), 'MIDDLE'),
        ('ALIGN',         (1,0), (4,-1), 'CENTER'),
    ] + row_styles))
    elements.append(tbl)
    elements.append(Spacer(1, 14))

    # Overall verdict
    total      = len(execution_results)
    pass_count = sum(1 for r in execution_results if r.get('status') == 'pass')
    fail_count = sum(1 for r in execution_results if r.get('status') == 'fail')
    pass_rate  = round(pass_count / total * 100) if total else 0

    if fail_count == 0 and pass_rate == 100:
        oc, ob, obrd = '#059669', HexColor('#f0fdf4'), GREEN
        oi = '🟢'
        ot = (f'All {total} API tests passed successfully. '
              f'The {framework} collection is stable and ready for CI/CD integration.')
    elif pass_rate >= 80:
        oc, ob, obrd = '#b45309', HexColor('#fffbeb'), ORANGE
        oi = '🟡'
        ot = (f'API validation passed with {fail_count} issue(s). '
              f'Core endpoints are operational but {fail_count} test(s) need investigation.')
    else:
        oc, ob, obrd = '#dc2626', HexColor('#fef2f2'), RED
        oi = '🔴'
        ot = (f'API validation FAILED — {fail_count}/{total} tests failed. '
              f'Critical endpoints may be down or authentication may have expired.')

    v_tbl = Table([[Paragraph(
        f'<font color="{oc}" size="9"><b>{oi}  Overall API Verdict: </b></font>'
        f'<font color="{oc}" size="8">{ot}</font>',
        ParagraphStyle('OV', fontSize=8, fontName='Helvetica', leading=13))
    ]], colWidths=[168*mm])
    v_tbl.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (-1,-1), ob),
        ('BOX',           (0,0), (-1,-1), 1.5, obrd),
        ('LEFTPADDING',   (0,0), (-1,-1), 12),
        ('RIGHTPADDING',  (0,0), (-1,-1), 12),
        ('TOPPADDING',    (0,0), (-1,-1), 10),
        ('BOTTOMPADDING', (0,0), (-1,-1), 10),
    ]))
    elements.append(v_tbl)
    elements.append(Spacer(1, 18))


# ── Section 7 : AI Recommendations ───────────────────────────────────────────

def build_api_recommendations(elements, execution_results: list, framework: str):
    elements.append(section_header('🤖', 'AI Recommendations', INDIGO))
    elements.append(Spacer(1, 4))
    elements.append(Paragraph(
        '<font color="#64748b" size="7.5"><i>'
        'Actionable recommendations derived from test results, '
        'LLaMA analysis, and API health signals.'
        '</i></font>',
        ParagraphStyle('ARInfo', fontSize=7.5, fontName='Helvetica', leading=10)))
    elements.append(Spacer(1, 12))

    total      = len(execution_results)
    pass_count = sum(1 for r in execution_results if r.get('status') == 'pass')
    fail_count = sum(1 for r in execution_results if r.get('status') == 'fail')
    skip_count = sum(1 for r in execution_results if r.get('status') == 'skip')
    pass_rate  = round(pass_count / total * 100) if total else 0

    failed_results = [r for r in execution_results if r.get('status') == 'fail']
    auth_failures  = [r for r in failed_results if r.get('category') == 'auth'
                      or r.get('http_status') in (401, 403)]
    slow_tests     = [r for r in execution_results
                      if _parse_duration_ms(r.get('duration', '—')) > 3000]
    assertion_failures = [r for r in execution_results
                          if any(not a.get('passed') for a in r.get('assertions_detail', []))]

    categories = []

    # ── Auth & Security ──
    auth_recs = []
    if auth_failures:
        auth_recs.append(
            f'{len(auth_failures)} test(s) returned 401/403. '
            f'Verify JWT token is valid and not expired. '
            f'Affected: {", ".join(r.get("name","")[:30] for r in auth_failures[:2])}.'
        )
    else:
        auth_recs.append('All authenticated endpoints accepted the JWT token. Auth layer is healthy.')
    if any(r.get('skip_auth') for r in execution_results if r.get('status') == 'fail'):
        auth_recs.append('Some unauthorized tests failed — verify the API correctly returns 401 for missing tokens.')
    categories.append(('🔐', 'Auth & Security', auth_recs, '#6366f1', INDIGO_BG))

    # ── Performance ──
    perf_recs = []
    avg_ms = _avg_duration_ms(execution_results)
    if avg_ms > 3000:
        perf_recs.append(
            f'Average response time is {avg_ms}ms — above 3s threshold. '
            f'Consider API-side caching and query optimization.'
        )
    elif avg_ms > 1000:
        perf_recs.append(f'Average response time is {avg_ms}ms — acceptable but can be improved.')
    else:
        perf_recs.append(f'Average response time is {avg_ms}ms — excellent API performance.')
    if slow_tests:
        perf_recs.append(
            f'{len(slow_tests)} test(s) exceeded 3s: '
            f'{", ".join(r.get("name","")[:25] for r in slow_tests[:3])}.'
        )
    categories.append(('⚡', 'Performance', perf_recs, '#f59e0b', ORANGE_BG))

    # ── Reliability ──
    rel_recs = []
    if fail_count == 0:
        rel_recs.append('All endpoints returned expected status codes. No reliability issues detected.')
    else:
        for r in failed_results[:4]:
            expected = r.get('expected_status', '—')
            actual   = r.get('http_status', '—')
            rel_recs.append(
                f'"{r.get("name","")[:40]}" expected {expected} but got {actual}. '
                f'{r.get("ai_analysis", {}).get("fix", "Review endpoint behavior.")[:60]}'
            )
    if skip_count > 0:
        rel_recs.append(f'{skip_count} test(s) skipped — verify preconditions and test data.')
    categories.append(('🔧', 'Reliability', rel_recs, '#10b981', GREEN_BG))

    # ── CI/CD ──
    fw_name, _, _, _ = _fw_display(framework)
    ci_recs = []
    if pass_rate == 100:
        ci_recs.append(f'{fw_name} collection is fully green — safe to integrate into CI/CD pipeline.')
        ci_recs.append('Consider scheduling automated runs on every deploy with Newman CLI: '
                       'newman run collection.json --environment env.json')
    elif pass_rate >= 80:
        ci_recs.append(f'{pass_rate}% pass rate — fix {fail_count} failing test(s) before CI/CD integration.')
        ci_recs.append('Use --bail flag in Newman to stop on first critical failure: '
                       'newman run collection.json --bail')
    else:
        ci_recs.append('Do not integrate into CI/CD until critical failures are resolved.')
        ci_recs.append('Run newman with verbose output to debug: newman run collection.json --verbose')
    categories.append(('🚀', 'CI/CD Integration', ci_recs, '#FF6C37', HexColor('#fff3ef')))

    for emoji, cat_label, recs, color_hex, bg_color in categories:
        color_obj = HexColor(color_hex) if isinstance(color_hex, str) else color_hex
        cat_tbl = Table([[Paragraph(
            f'<font color="{color_hex if isinstance(color_hex, str) else "#" + color_hex.hexval()[2:]}">'
            f'<b>{emoji}  {cat_label}</b></font>',
            ParagraphStyle('ARCAT', fontSize=9, fontName='Helvetica-Bold', leading=12))
        ]], colWidths=[168*mm])
        cat_tbl.setStyle(TableStyle([
            ('BACKGROUND',    (0,0), (-1,-1), bg_color),
            ('LEFTPADDING',   (0,0), (-1,-1), 10),
            ('TOPPADDING',    (0,0), (-1,-1), 7),
            ('BOTTOMPADDING', (0,0), (-1,-1), 7),
            ('BOX',           (0,0), (-1,-1), 1, color_obj),
        ]))
        elements.append(cat_tbl)

        for rec_text in recs:
            rec_tbl = Table([[Paragraph(
                f'<font color="#64748b" size="7.5">•  {rec_text}</font>',
                ParagraphStyle('ARREC', fontSize=7.5, fontName='Helvetica', leading=11))
            ]], colWidths=[168*mm])
            rec_tbl.setStyle(TableStyle([
                ('BACKGROUND',    (0,0), (-1,-1), HexColor('#fafafa')),
                ('LEFTPADDING',   (0,0), (-1,-1), 16),
                ('TOPPADDING',    (0,0), (-1,-1), 5),
                ('BOTTOMPADDING', (0,0), (-1,-1), 5),
                ('LINEBELOW',     (0,0), (-1,-1), 0.3, BORDER),
                ('LINEBEFORE',    (0,0), (0,-1),  2, color_obj),
            ]))
            elements.append(rec_tbl)
        elements.append(Spacer(1, 8))

    # Final verdict
    if fail_count == 0:
        vc, vb, vbrd = '#059669', HexColor('#f0fdf4'), GREEN
        vi = '🟢'
        vt = (f'API test suite passed 100%. {fw_name} collection validated successfully. '
              f'Ready for production deployment and CI/CD integration.')
    elif pass_rate >= 80:
        vc, vb, vbrd = '#b45309', HexColor('#fffbeb'), ORANGE
        vi = '🟡'
        vt = (f'{pass_rate}% pass rate with {fail_count} issue(s). '
              f'Core API functionality is stable — address failing tests before go-live.')
    else:
        vc, vb, vbrd = '#dc2626', HexColor('#fef2f2'), RED
        vi = '🔴'
        vt = (f'API validation FAILED ({pass_rate}% pass rate). '
              f'Critical endpoints are not responding as expected. Do not deploy.')

    quality_score = max(0, min(100, pass_rate - len(slow_tests) * 3))
    risk = 'LOW' if quality_score >= 80 else 'MEDIUM' if quality_score >= 60 else 'HIGH'
    risk_color = '#10b981' if quality_score >= 80 else '#f59e0b' if quality_score >= 60 else '#ef4444'

    final_tbl = Table([[Paragraph(
        f'<font color="{vc}" size="9"><b>{vi}  Final API Verdict</b></font><br/>'
        f'<font color="{vc}" size="8">{vt}</font><br/><br/>'
        f'<font color="#64748b" size="8"><b>Quality Score: </b></font>'
        f'<font color="{vc}" size="8"><b>{quality_score}/100</b></font>'
        f'<font color="#94a3b8" size="8">    |    </font>'
        f'<font color="#64748b" size="8"><b>Risk Level: </b></font>'
        f'<font color="{risk_color}" size="8"><b>{risk}</b></font>',
        ParagraphStyle('FAV', fontSize=8, fontName='Helvetica', leading=13))
    ]], colWidths=[168*mm])
    final_tbl.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (-1,-1), vb),
        ('BOX',           (0,0), (-1,-1), 2, vbrd),
        ('LEFTPADDING',   (0,0), (-1,-1), 14),
        ('RIGHTPADDING',  (0,0), (-1,-1), 14),
        ('TOPPADDING',    (0,0), (-1,-1), 12),
        ('BOTTOMPADDING', (0,0), (-1,-1), 12),
    ]))
    elements.append(final_tbl)
    elements.append(Spacer(1, 20))


# ── Section 8 : Script Summary ────────────────────────────────────────────────

def build_api_script_summary(elements, framework: str, test_cases: list,
                              script_postman: str = '', script_pytest: str = ''):
    fw_name, fw_color, fw_bg, fw_short = _fw_display(framework)
    elements.append(section_header('📄', f'Generated Script Summary — {fw_name}'))
    elements.append(Spacer(1, 4))
    elements.append(Paragraph(
        '<font color="#94a3b8" size="7.5"><i>'
        'Summary of the AI-generated API test collection/script. '
        'Full file available as a separate download.'
        '</i></font>',
        ParagraphStyle('SSInfo', fontSize=7.5, fontName='Helvetica', leading=10)))
    elements.append(Spacer(1, 10))

    total = len(test_cases)
    edge_count = sum(1 for tc in test_cases if tc.get('is_edge_case'))
    domains = list(dict.fromkeys(tc.get('category', 'api') for tc in test_cases))
    methods = list(dict.fromkeys(tc.get('method', 'GET').upper() for tc in test_cases))

    is_postman = 'postman' in framework.lower() or 'newman' in framework.lower()
    script_content = script_postman if is_postman else script_pytest
    has_env_vars   = '{{token}}' in (script_content or '') or '{{BASE_URL}}' in (script_content or '')
    has_tests      = '"exec"' in (script_content or '') or 'pm.test' in (script_content or '')

    summary_rows = [
        [_lbl_w('Tests Generated'),
         Paragraph(f'<font color="#1e293b"><b>{total}</b></font>'
                   f'<font color="#64748b" size="7.5"> test case(s) — {edge_count} edge case(s)</font>',
                   ParagraphStyle('SSV1', fontSize=8, fontName='Helvetica', leading=11))],
        [_lbl_w('Framework'),
         Paragraph(f'<font color="{fw_color}"><b>{fw_name}</b></font>',
                   ParagraphStyle('SSV2', fontSize=8, fontName='Helvetica-Bold', leading=11))],
        [_lbl_w('Domains Covered'),
         Paragraph(f'<font color="#4f46e5">{", ".join(d.upper() for d in domains)}</font>',
                   ParagraphStyle('SSV3', fontSize=8, fontName='Helvetica', leading=11))],
        [_lbl_w('HTTP Methods'),
         Paragraph(
             '  '.join(
                 f'<font color="{METHOD_COLORS.get(m, ("#64748b","#f8fafc"))[0]}"><b>{m}</b></font>'
                 for m in methods),
             ParagraphStyle('SSV4', fontSize=8, fontName='Helvetica', leading=11))],
    ]

    if is_postman:
        summary_rows += [
            [_lbl_w('Collection Format'),
             Paragraph('<font color="#1e293b">Postman Collection v2.1 (JSON)</font>',
                       ParagraphStyle('SSV5', fontSize=8, fontName='Helvetica', leading=11))],
            [_lbl_w('Environment Variables'),
             Paragraph(
                 '<font color="#10b981"><b>Configured</b></font>' if has_env_vars
                 else '<font color="#f59e0b"><b>Not configured</b></font>',
                 ParagraphStyle('SSV6', fontSize=8, fontName='Helvetica-Bold', leading=11))],
            [_lbl_w('Test Scripts'),
             Paragraph(
                 '<font color="#10b981"><b>pm.test() assertions included</b></font>' if has_tests
                 else '<font color="#f59e0b"><b>No test scripts</b></font>',
                 ParagraphStyle('SSV7', fontSize=8, fontName='Helvetica-Bold', leading=11))],
            [_lbl_w('Newman CLI'),
             Paragraph(
                 '<font color="#64748b">newman run collection.json '
                 '--environment env.json --reporters cli,json</font>',
                 ParagraphStyle('SSV8', fontSize=7.5, fontName='Courier', leading=11))],
        ]
    else:
        summary_rows += [
            [_lbl_w('Script Format'),
             Paragraph('<font color="#1e293b">Python — pytest + requests</font>',
                       ParagraphStyle('SSV5', fontSize=8, fontName='Helvetica', leading=11))],
            [_lbl_w('SSL Verification'),
             Paragraph('<font color="#10b981"><b>Disabled (self-signed cert support)</b></font>',
                       ParagraphStyle('SSV6', fontSize=8, fontName='Helvetica-Bold', leading=11))],
            [_lbl_w('Run Command'),
             Paragraph(
                 '<font color="#64748b">pytest test_api_pytest.py -v --tb=short</font>',
                 ParagraphStyle('SSV8', fontSize=7.5, fontName='Courier', leading=11))],
        ]

    # Build the header row
    full_rows = [[
        Paragraph('<font color="#ffffff"><b>Property</b></font>',
                  ParagraphStyle('SSH1', fontSize=8, fontName='Helvetica-Bold')),
        Paragraph('<font color="#ffffff"><b>Value</b></font>',
                  ParagraphStyle('SSH2', fontSize=8, fontName='Helvetica-Bold')),
    ]] + summary_rows

    sum_tbl = Table(full_rows, colWidths=[45*mm, 123*mm])
    sum_tbl.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (-1,0), NAVY),
        ('BACKGROUND',    (0,1), (0,-1), LIGHT_BG),
        ('ROWBACKGROUNDS',(0,1), (-1,-1), [WHITE, LIGHT_BG]),
        ('PADDING',       (0,0), (-1,-1), 8),
        ('LINEBELOW',     (0,0), (-1,-2), 0.4, BORDER),
        ('BOX',           (0,0), (-1,-1), 0.8, BORDER_DARK),
        ('VALIGN',        (0,0), (-1,-1), 'MIDDLE'),
        ('LEFTPADDING',   (0,0), (0,-1), 10),
    ]))
    elements.append(sum_tbl)
    elements.append(Spacer(1, 6))
    elements.append(Paragraph(
        '<font color="#94a3b8" size="7"><i>'
        '* Full collection/script available as a separate download. '
        'Raw code omitted to keep the report concise.'
        '</i></font>',
        ParagraphStyle('ScriptNote', fontSize=7, fontName='Helvetica', leading=10,
                       alignment=TA_CENTER)))
    elements.append(Spacer(1, 20))


# ── Main Entry Point ───────────────────────────────────────────────────────────

def generate_api_pdf(generation_data: dict) -> bytes:
    """
    Main entry point — called from main.py for API test PDF reports.

    Expected generation_data structure (from /generate-api route):
    {
        "url": str,
        "framework": str,  # "Postman" | "Pytest" | "Newman"
        "test_type": "api",
        "result": {
            "test_cases": [...],          # from api_generator.py (with status from runner)
            "execution_results": [...],   # from api_runner.py
            "script_postman": str,
            "script_pytest": str,
            "domains": [...],
            "base_url": str,
            "pass_count": int,
            "fail_count": int,
            "skip_count": int,
            "pass_rate": int,
        }
    }
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        rightMargin=20*mm, leftMargin=22*mm,
        topMargin=58*mm, bottomMargin=20*mm
    )

    url       = generation_data.get('url', '')
    framework = generation_data.get('framework', 'Postman')
    result    = generation_data.get('result', generation_data)

    test_cases        = result.get('test_cases', [])
    execution_results = result.get('execution_results', test_cases)
    script_postman    = result.get('script_postman', '')
    script_pytest     = result.get('script_pytest', '')
    domains           = result.get('domains', [])
    base_url          = result.get('base_url', url)
    pass_count        = result.get('pass_count', sum(1 for r in execution_results if r.get('status') == 'pass'))
    fail_count        = result.get('fail_count', sum(1 for r in execution_results if r.get('status') == 'fail'))
    skip_count        = result.get('skip_count', sum(1 for r in execution_results if r.get('status') == 'skip'))
    pass_rate         = result.get('pass_rate', round(pass_count / len(execution_results) * 100) if execution_results else 0)

    fw_name, fw_color, fw_bg, fw_short = _fw_display(framework)

    elements = []

    # ── Header ──────────────────────────────────────────────────────────────
    header_data = [[
        Paragraph(
            '<font color="#c9a227"><b>NEX</b></font><font color="#ffffff">TEST</font>',
            ParagraphStyle('Logo', fontSize=24, fontName='Helvetica-Bold')),
        Paragraph(
            f'<font color="#64748b">Generated</font><br/>'
            f'<font color="#94a3b8">{datetime.now().strftime("%B %d, %Y  •  %H:%M")}</font>',
            ParagraphStyle('Date', fontSize=8.5, fontName='Helvetica',
                           alignment=TA_RIGHT, leading=13)),
    ]]
    header_tbl = Table(header_data, colWidths=[90*mm, 78*mm])
    header_tbl.setStyle(TableStyle([
        ('VALIGN',        (0,0), (-1,-1), 'MIDDLE'),
        ('TOPPADDING',    (0,0), (-1,-1), 0),
        ('BOTTOMPADDING', (0,0), (-1,-1), 0),
    ]))
    elements.append(Spacer(1, -38*mm))
    elements.append(header_tbl)
    elements.append(Spacer(1, 6*mm))
    elements.append(Paragraph(
        'API Test Report',
        ParagraphStyle('Title', fontSize=22, textColor=white,
                       fontName='Helvetica-Bold', spaceAfter=2)))
    elements.append(Spacer(1, 14*mm))

    # ── Info Box ─────────────────────────────────────────────────────────────
    rate_color = '#10b981' if pass_rate >= 80 else '#f59e0b' if pass_rate >= 50 else '#ef4444'
    total_tests = len(execution_results)

    info_rows = [
        [_lbl('URL'),          _val(url)],
        [_lbl('Base API URL'), _val(base_url)],
        [_lbl('Framework'),    Paragraph(
            f'<font color="{fw_color}"><b>{fw_name}</b></font>',
            ParagraphStyle('FWI', fontSize=8.5, fontName='Helvetica', leading=12))],
        [_lbl('Domains'),      _val(', '.join(d.upper() for d in domains) if domains else 'AUTO')],
        [_lbl('Results'),      Paragraph(
            f'<font color="#10b981"><b>{pass_count} pass</b></font>'
            f'<font color="#94a3b8">  /  </font>'
            f'<font color="#ef4444"><b>{fail_count} fail</b></font>'
            f'<font color="#94a3b8">  /  </font>'
            f'<font color="#f59e0b"><b>{skip_count} skip</b></font>'
            f'<font color="#94a3b8">  —  </font>'
            f'<font color="{rate_color}"><b>{pass_rate}% pass rate</b></font>',
            ParagraphStyle('RES', fontSize=8.5, fontName='Helvetica', leading=12))],
        [_lbl('Generated'),    _val(datetime.now().strftime('%Y-%m-%d  %H:%M'))],
    ]
    info_tbl = Table(info_rows, colWidths=[32*mm, 136*mm])
    info_tbl.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (0,-1), LIGHT_BG),
        ('ROWBACKGROUNDS',(0,0), (-1,-1), [WHITE, LIGHT_BG]),
        ('PADDING',       (0,0), (-1,-1), 7),
        ('LINEBELOW',     (0,0), (-1,-2), 0.4, BORDER),
        ('BOX',           (0,0), (-1,-1), 0.8, BORDER_DARK),
        ('LEFTPADDING',   (0,0), (0,-1), 10),
        ('VALIGN',        (0,0), (-1,-1), 'MIDDLE'),
    ]))
    elements.append(info_tbl)
    elements.append(Spacer(1, 20))

    # ── Framework Banner ─────────────────────────────────────────────────────
    fw_banner = Table([[Paragraph(
        f'<font color="{fw_color}"><b>  {fw_short}  {fw_name.upper()}</b></font>',
        ParagraphStyle('FWB', fontSize=11, fontName='Helvetica-Bold', leading=14))
    ]], colWidths=[168*mm])
    fw_banner.setStyle(TableStyle([
    ('BACKGROUND',    (0,0), (-1,-1), fw_bg),
    ('BOX',           (0,0), (-1,-1), 1.5, HexColor(fw_color)),
        ('TOPPADDING',    (0,0), (-1,-1), 8),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('LEFTPADDING',   (0,0), (-1,-1), 12),
    ]))
    elements.append(fw_banner)
    elements.append(Spacer(1, 16))

    # ── All Sections ─────────────────────────────────────────────────────────
    build_api_test_plan(elements, test_cases, base_url, framework, domains)

    elements.append(section_header('📊', 'Test Summary', GOLD))
    elements.append(Spacer(1, 8))
    build_api_stats_section(elements, execution_results)

    build_api_execution_results(elements, execution_results)
    build_api_assertions_detail(elements, execution_results)
    build_api_llama_analysis(elements, execution_results)
    build_api_verdict_summary(elements, execution_results, framework)
    build_api_recommendations(elements, execution_results, framework)
    build_api_script_summary(elements, framework, test_cases, script_postman, script_pytest)

    # ── Footer ───────────────────────────────────────────────────────────────
    elements.append(Spacer(1, 10))
    footer_data = [[
        Paragraph(
            '<font color="#64748b" size="10"><b>NEX</b></font>'
            '<font color="#c9a227" size="10"><b>TEST</b></font>'
            '<font color="#94a3b8" size="8">  ·  AI-Powered API Test Automation</font>',
            ParagraphStyle('FTR', fontSize=10, fontName='Helvetica', leading=14)),
        Paragraph(
            f'<font color="#94a3b8" size="7">'
            f'Generated {datetime.now().strftime("%Y-%m-%d")}  ·  '
            f'{fw_name}  ·  {total_tests} tests  ·  {pass_rate}% pass rate'
            f'</font>',
            ParagraphStyle('FTRD', fontSize=7, fontName='Helvetica',
                           alignment=TA_RIGHT, leading=10)),
    ]]
    footer_tbl = Table(footer_data, colWidths=[84*mm, 84*mm])
    footer_tbl.setStyle(TableStyle([
        ('VALIGN',        (0,0), (-1,-1), 'MIDDLE'),
        ('BACKGROUND',    (0,0), (-1,-1), LIGHT_BG),
        ('BOX',           (0,0), (-1,-1), 0.5, BORDER),
        ('LEFTPADDING',   (0,0), (-1,-1), 10),
        ('RIGHTPADDING',  (0,0), (-1,-1), 10),
        ('TOPPADDING',    (0,0), (-1,-1), 8),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
    ]))
    elements.append(footer_tbl)

    doc.build(elements, onFirstPage=on_page_api, onLaterPages=on_page_api)
    return buffer.getvalue()


# ── Private Helpers ────────────────────────────────────────────────────────────

def _lbl(text: str):
    return Paragraph(f'<font color="#64748b">{text}</font>',
                     ParagraphStyle('IL', fontSize=8, fontName='Helvetica-Bold', leading=12))

def _lbl_w(text: str):
    return Paragraph(f'<font color="#64748b"><b>{text}</b></font>',
                     ParagraphStyle('ILW', fontSize=8, fontName='Helvetica-Bold', leading=11))

def _val(text: str):
    return Paragraph(f'<font color="#1e293b">{text}</font>',
                     ParagraphStyle('IV', fontSize=8.5, fontName='Helvetica', leading=12))

def _status_code_badge(code) -> str:
    c = int(code) if str(code).isdigit() else 0
    if c == 200 or c == 201:   color = '#10b981'
    elif c == 401 or c == 403: color = '#f59e0b'
    elif c == 404:              color = '#3b82f6'
    elif c == 422:              color = '#8b5cf6'
    elif c >= 500:              color = '#ef4444'
    else:                       color = '#64748b'
    return f'<font color="{color}"><b>{code}</b></font>'

def _status_result_colors(status: str) -> tuple:
    """Returns (text_color_hex, bg_color_hex)"""
    if status == 'pass':   return '#10b981', '#f0fdf4'
    elif status == 'fail': return '#ef4444', '#fef2f2'
    else:                  return '#f59e0b', '#fffbeb'

def _avg_duration(execution_results: list) -> str:
    ms = _avg_duration_ms(execution_results)
    if ms == 0: return '—'
    return f'{ms}ms' if ms < 1000 else f'{ms/1000:.1f}s'

def _avg_duration_ms(execution_results: list) -> int:
    vals = []
    for r in execution_results:
        ms = _parse_duration_ms(r.get('duration', '—'))
        if ms > 0:
            vals.append(ms)
    return round(sum(vals) / len(vals)) if vals else 0

def _parse_duration_ms(duration: str) -> int:
    if not duration or duration == '—':
        return 0
    try:
        d = str(duration).strip().lower()
        if d.endswith('ms'):  return int(float(d[:-2]))
        elif d.endswith('s'): return int(float(d[:-1]) * 1000)
        return int(float(d))
    except Exception:
        return 0