from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor, white, black
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable, KeepTogether
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.platypus import Flowable
from io import BytesIO
from datetime import datetime

# ── Color Palette ──────────────────────────────────────────────
NAVY        = HexColor('#0a0f1e')
GOLD        = HexColor('#c9a227')
GREEN       = HexColor('#10b981')
GREEN_BG    = HexColor('#d1fae5')
RED         = HexColor('#ef4444')
RED_BG      = HexColor('#fee2e2')
ORANGE      = HexColor('#f59e0b')
ORANGE_BG   = HexColor('#fef3c7')
BLUE        = HexColor('#3b82f6')
BLUE_BG     = HexColor('#dbeafe')
LIGHT_BG    = HexColor('#f8fafc')
BORDER      = HexColor('#e2e8f0')
BORDER_DARK = HexColor('#cbd5e1')
MUTED       = HexColor('#94a3b8')
DARK_TEXT   = HexColor('#1e293b')
WHITE       = white

SELENIUM_COLOR = HexColor('#43a047')
SELENIUM_BG    = HexColor('#e8f5e9')
CYPRESS_COLOR  = HexColor('#1565c0')
CYPRESS_BG     = HexColor('#e3f2fd')

# ── Priority colors ────────────────────────────────────────────
PRIORITY_COLORS = {
    'high':   '#ef4444',
    'medium': '#f59e0b',
    'low':    '#10b981',
}
CATEGORY_COLORS = {
    'functional':  '#3b82f6',
    'performance': '#8b5cf6',
    'ui':          '#ec4899',
    'security':    '#ef4444',
    'navigation':  '#10b981',
}


def on_page(canvas, doc):
    W, H = A4
    canvas.saveState()
    canvas.setFillColor(NAVY)
    canvas.rect(0, H - 52*mm, W, 52*mm, fill=1, stroke=0)
    canvas.setFillColor(GOLD)
    canvas.rect(0, H - 54*mm, W, 2*mm, fill=1, stroke=0)
    canvas.setFillColor(GOLD)
    canvas.rect(0, 0, 3, H - 54*mm, fill=1, stroke=0)
    canvas.setFillColor(LIGHT_BG)
    canvas.rect(0, 0, W, 14*mm, fill=1, stroke=0)
    canvas.setFillColor(BORDER)
    canvas.rect(0, 14*mm, W, 0.5, fill=1, stroke=0)
    canvas.setFont('Helvetica', 7.5)
    canvas.setFillColor(MUTED)
    canvas.drawString(20*mm, 5*mm, 'Generated by NexTest — AI-Powered Test Automation Platform')
    canvas.drawRightString(W - 20*mm, 5*mm, f'Page {doc.page}  •  {datetime.now().strftime("%Y-%m-%d")}')
    canvas.restoreState()


def section_header(emoji, text):
    data = [[Paragraph(f'{emoji}  {text}',
                       ParagraphStyle('SH', fontSize=11, fontName='Helvetica-Bold',
                                      textColor=DARK_TEXT, leading=14))]]
    tbl = Table(data, colWidths=[168*mm])
    tbl.setStyle(TableStyle([
        ('LINEBELOW',     (0,0), (-1,-1), 1.5, GOLD),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ('TOPPADDING',    (0,0), (-1,-1), 0),
    ]))
    return tbl


def framework_banner(label, color, bg):
    data = [[Paragraph(label, ParagraphStyle(
        'FB', fontSize=11, fontName='Helvetica-Bold', textColor=color, leading=14))]]
    tbl = Table(data, colWidths=[168*mm])
    tbl.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (-1,-1), bg),
        ('BOX',           (0,0), (-1,-1), 1, color),
        ('TOPPADDING',    (0,0), (-1,-1), 6),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ('LEFTPADDING',   (0,0), (-1,-1), 10),
    ]))
    return tbl


def stat_card(value, label, val_color, bg_color):
    inner = [[Paragraph(
        f'<font color="{val_color}"><b>{value}</b></font><br/>'
        f'<font color="#94a3b8" size="7"><b>{label}</b></font>',
        ParagraphStyle('SC', fontSize=18, fontName='Helvetica-Bold', alignment=TA_CENTER, leading=26))]]
    t = Table(inner, colWidths=[30*mm])
    t.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (-1,-1), bg_color),
        ('BOX',           (0,0), (-1,-1), 1, BORDER_DARK),
        ('TOPPADDING',    (0,0), (-1,-1), 12),
        ('BOTTOMPADDING', (0,0), (-1,-1), 12),
        ('ALIGN',         (0,0), (-1,-1), 'CENTER'),
    ]))
    return t


def _get_status(tc_index: int, tc_type: str, execution_results: list) -> tuple:
    if execution_results and tc_index < len(execution_results):
        s = execution_results[tc_index].get('status', 'skip')
        if s == 'pass':   return '#10b981', '✓  PASS'
        elif s == 'fail': return '#ef4444', '✗  FAIL'
        else:             return '#f59e0b', '■  SKIP'
    if tc_type == 'positive':  return '#10b981', '✓  PASS'
    elif tc_type == 'negative': return '#ef4444', '✗  FAIL'
    else: return '#f59e0b', '■  SKIP'


def _get_reason_text(tc_index: int, tc: dict, execution_results: list) -> tuple:
    """
    Retourne (reason_text, reason_color, bg_color) avec raison détaillée.
    Utilise reason_pass / reason / reason_skip depuis runner.py.
    """
    tc_type  = tc.get('type', 'positive')
    expected = tc.get('expected', '')

    # ── Pas de résultats d'exécution → fallback sur le type ──
    if not execution_results or tc_index >= len(execution_results):
        if tc_type == 'positive':
            return "Test positif — verifie le comportement attendu.", '#059669', HexColor('#f0fdf4')
        elif tc_type == 'negative':
            return "Test negatif — verifie la gestion des erreurs.", '#dc2626', HexColor('#fef2f2')
        else:
            return "Test ignore — conditions non remplies.", '#b45309', HexColor('#fffbeb')

    exec_r = execution_results[tc_index]
    status = exec_r.get('status', 'skip')

    if status == 'pass':
        reason = exec_r.get('reason_pass') or "Test reussi — toutes les assertions validees."
        return reason, '#059669', HexColor('#f0fdf4')

    elif status == 'fail':
        reason = exec_r.get('reason') or exec_r.get('error') or "Test echoue — voir le script pour details."
        return reason, '#dc2626', HexColor('#fef2f2')

    else:
        reason = exec_r.get('reason_skip') or "Test ignore — element ou condition non detecte."
        return reason, '#b45309', HexColor('#fffbeb')


def _calc_stats(test_cases: list, execution_results: list) -> tuple:
    total = len(test_cases)
    if not total: return 0, 0, 0, 0

    if execution_results:
        pass_count = sum(1 for r in execution_results if r.get('status') == 'pass')
        fail_count = sum(1 for r in execution_results if r.get('status') == 'fail')
        skip_count = sum(1 for r in execution_results if r.get('status') == 'skip')
        skip_count += max(total - len(execution_results), 0)
    else:
        pass_count = sum(1 for t in test_cases if t.get('type') == 'positive')
        fail_count = sum(1 for t in test_cases if t.get('type') == 'negative')
        skip_count = total - pass_count - fail_count

    rate = round((pass_count / total) * 100) if total > 0 else 0
    return pass_count, fail_count, skip_count, rate


def build_stats_section(elements, test_cases, execution_results=None):
    pass_count, fail_count, skip_count, rate = _calc_stats(test_cases, execution_results or [])
    total    = len(test_cases)
    rate_hex = '#10b981' if rate >= 80 else '#f59e0b' if rate >= 50 else '#ef4444'
    rate_bg  = GREEN_BG  if rate >= 80 else ORANGE_BG  if rate >= 50 else RED_BG

    stats_data = [[
        stat_card(pass_count, 'PASSED',    '#10b981', GREEN_BG),
        stat_card(fail_count, 'FAILED',    '#ef4444', RED_BG),
        stat_card(skip_count, 'SKIPPED',   '#f59e0b', ORANGE_BG),
        stat_card(f'{rate}%', 'PASS RATE', rate_hex,  rate_bg),
        stat_card(total,      'TOTAL',     '#3b82f6', BLUE_BG),
    ]]
    outer = Table(stats_data, colWidths=[33.6*mm]*5)
    outer.setStyle(TableStyle([
        ('ALIGN',  (0,0), (-1,-1), 'CENTER'),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('PADDING',(0,0), (-1,-1), 2),
    ]))
    elements.append(outer)


def build_test_cases_table(elements, test_cases, execution_results=None):
    # ── 5 colonnes: #, Test Name + badges, Status, Expected, Reason détaillée ──
    col_w = [8*mm, 48*mm, 20*mm, 42*mm, 50*mm]

    header_row = [
        Paragraph('<font color="#ffffff"><b>#</b></font>',
                  ParagraphStyle('TH', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
        Paragraph('<font color="#ffffff"><b>Test Name</b></font>',
                  ParagraphStyle('TH', fontSize=8, fontName='Helvetica-Bold')),
        Paragraph('<font color="#ffffff"><b>Status</b></font>',
                  ParagraphStyle('TH', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
        Paragraph('<font color="#ffffff"><b>Expected</b></font>',
                  ParagraphStyle('TH', fontSize=8, fontName='Helvetica-Bold')),
        Paragraph('<font color="#ffffff"><b>Reason</b></font>',
                  ParagraphStyle('TH', fontSize=8, fontName='Helvetica-Bold')),
    ]
    tc_rows    = [header_row]
    row_styles = []

    for i, tc in enumerate(test_cases):
        tc_type   = tc.get('type', 'positive')
        priority  = tc.get('priority', 'medium')
        category  = tc.get('category', 'functional')

        type_color, type_label          = _get_status(i, tc_type, execution_results or [])
        reason_text, reason_color, reason_bg = _get_reason_text(i, tc, execution_results or [])

        # ── Couleurs des badges priority et category ──
        pri_color = PRIORITY_COLORS.get(priority, '#94a3b8')
        cat_color = CATEGORY_COLORS.get(category, '#3b82f6')

        # ── Tronquer les textes ──
        desc_short   = tc.get('description', '')
        desc_short   = desc_short[:60] + '…' if len(desc_short) > 60 else desc_short
        exp_short    = tc.get('expected', '')
        exp_short    = exp_short[:55] + '…' if len(exp_short) > 55 else exp_short
        reason_short = reason_text[:180] + '…' if len(reason_text) > 180 else reason_text

        # ── Colonne 2: Nom + description + badges priority/category ──
        name_cell = Paragraph(
            f'<b><font color="#1e293b" size="8.5">{tc.get("name","")}</font></b><br/>'
            f'<font color="#94a3b8" size="6.5">{desc_short}</font><br/>'
            f'<font color="{pri_color}" size="6"><b>{priority.upper()}</b></font>'
            f'<font color="#94a3b8" size="6">  |  </font>'
            f'<font color="{cat_color}" size="6"><b>{category.upper()}</b></font>',
            ParagraphStyle('TCN', fontSize=8.5, fontName='Helvetica', leading=11)
        )

        # ── Colonne 5: Reason avec icône selon statut ──
        status_icon = '✓' if type_label.startswith('✓') else '✗' if type_label.startswith('✗') else '■'
        reason_cell = Paragraph(
            f'<font color="{reason_color}" size="7"><b>{status_icon}</b> {reason_short}</font>',
            ParagraphStyle('RSN', fontSize=7, fontName='Helvetica', leading=9.5)
        )

        tc_rows.append([
            Paragraph(f'<font color="#64748b"><b>{tc.get("id","")}</b></font>',
                      ParagraphStyle('IDC', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
            name_cell,
            Paragraph(
                f'<font color="{type_color}"><b>{type_label}</b></font>',
                ParagraphStyle('TYP', fontSize=7.5, fontName='Helvetica-Bold', alignment=TA_CENTER)),
            Paragraph(
                f'<font color="#475569" size="7.5">{exp_short}</font>',
                ParagraphStyle('EXP', fontSize=7.5, fontName='Helvetica', leading=10)),
            reason_cell,
        ])

        # ── Fond coloré pour la colonne Reason selon statut ──
        row_idx = i + 1  # +1 pour le header
        row_styles.append(('BACKGROUND', (4, row_idx), (4, row_idx), reason_bg))

    tc_tbl = Table(tc_rows, colWidths=col_w, repeatRows=1)

    base_style = [
        ('BACKGROUND',    (0,0), (-1,0), NAVY),
        ('TEXTCOLOR',     (0,0), (-1,0), WHITE),
        ('FONTNAME',      (0,0), (-1,0), 'Helvetica-Bold'),
        ('TOPPADDING',    (0,0), (-1,0), 9),
        ('BOTTOMPADDING', (0,0), (-1,0), 9),
        ('ROWBACKGROUNDS',(0,1), (-1,-1), [WHITE, LIGHT_BG]),
        ('PADDING',       (0,1), (-1,-1), 7),
        ('LINEBELOW',     (0,0), (-1,-1), 0.4, BORDER),
        ('BOX',           (0,0), (-1,-1), 0.8, BORDER_DARK),
        ('VALIGN',        (0,0), (-1,-1), 'TOP'),
        ('ALIGN',         (0,0), (0,-1), 'CENTER'),
        ('ALIGN',         (2,0), (2,-1), 'CENTER'),
        # Bordure gauche colorée sur la colonne Reason
        ('LINEBEFORE',    (4,1), (4,-1), 1.5, BORDER_DARK),
    ]

    tc_tbl.setStyle(TableStyle(base_style + row_styles))
    elements.append(tc_tbl)


def build_script_section(elements, script, framework_label):
    if not script:
        return
    elements.append(Spacer(1, 18))
    elements.append(section_header('📄', f'AI-Generated {framework_label} Script'))
    elements.append(Spacer(1, 4))
    elements.append(Paragraph(
        "<font color='#94a3b8'><i>Ce script a ete genere automatiquement par l'IA pour tester votre site.</i></font>",
        ParagraphStyle('Info', fontSize=7.5, fontName='Helvetica')))
    elements.append(Spacer(1, 6))

    lines = script.replace('\\n', '\n').split('\n')[:60]
    code_rows = []
    for ln_no, line in enumerate(lines, 1):
        safe = line.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
        code_rows.append([
            Paragraph(f'<font color="#94a3b8">{ln_no}</font>',
                      ParagraphStyle('LN', fontSize=7, fontName='Courier', alignment=TA_RIGHT, leading=12)),
            Paragraph(safe or ' ',
                      ParagraphStyle('CL', fontSize=7.8, fontName='Courier',
                                     textColor=HexColor('#1e293b'), leading=12)),
        ])

    code_tbl = Table(code_rows, colWidths=[10*mm, 158*mm])
    code_tbl.setStyle(TableStyle([
        ('BACKGROUND',  (0,0), (-1,-1), HexColor('#f8fafc')),
        ('BACKGROUND',  (0,0), (0,-1),  HexColor('#f1f5f9')),
        ('PADDING',     (0,0), (-1,-1), 3),
        ('LEFTPADDING', (0,0), (0,-1),  6),
        ('RIGHTPADDING',(0,0), (0,-1),  6),
        ('LEFTPADDING', (1,0), (1,-1),  8),
        ('BOX',         (0,0), (-1,-1), 1, BORDER_DARK),
        ('LINEAFTER',   (0,0), (0,-1),  0.5, BORDER_DARK),
        ('VALIGN',      (0,0), (-1,-1), 'TOP'),
    ]))
    elements.append(code_tbl)

    if len(script.split('\n')) > 60:
        elements.append(Spacer(1, 4))
        elements.append(Paragraph(
            '<font color="#94a3b8"><i>... script truncated — download full version for complete output</i></font>',
            ParagraphStyle('Trunc', fontSize=7.5, fontName='Helvetica', alignment=TA_CENTER)))


def generate_pdf(generation_data: dict) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                            rightMargin=20*mm, leftMargin=22*mm,
                            topMargin=58*mm, bottomMargin=20*mm)

    url       = generation_data.get('url', '')
    framework = generation_data.get('framework', 'Selenium')
    load_time = generation_data.get('load_time_ms', 0)
    is_spa    = generation_data.get('is_spa', False)

    test_cases          = generation_data.get('test_cases', [])
    test_cases_selenium = generation_data.get('test_cases_selenium', [])
    test_cases_cypress  = generation_data.get('test_cases_cypress', [])
    script              = generation_data.get('script', '')
    script_selenium     = generation_data.get('script_selenium', '')
    script_cypress      = generation_data.get('script_cypress', '')
    execution_results   = generation_data.get('execution_results', [])

    elements = []

    # ── Header ────────────────────────────────────────────────
    header_data = [[
        Paragraph('<font color="#c9a227"><b>NEX</b></font><font color="#ffffff">TEST</font>',
                  ParagraphStyle('Logo', fontSize=24, fontName='Helvetica-Bold')),
        Paragraph(f'<font color="#64748b">Generated</font><br/>'
                  f'<font color="#94a3b8">{datetime.now().strftime("%B %d, %Y  •  %H:%M")}</font>',
                  ParagraphStyle('Date', fontSize=8.5, fontName='Helvetica', alignment=TA_RIGHT, leading=13))
    ]]
    header_tbl = Table(header_data, colWidths=[90*mm, 78*mm])
    header_tbl.setStyle(TableStyle([
        ('VALIGN',        (0,0), (-1,-1), 'MIDDLE'),
        ('TOPPADDING',    (0,0), (-1,-1), 0),
        ('BOTTOMPADDING', (0,0), (-1,-1), 0),
    ]))
    elements.append(Spacer(1, -38*mm))
    elements.append(header_tbl)
    elements.append(Spacer(1, 6*mm))
    elements.append(Paragraph('Test Automation Report',
                               ParagraphStyle('Title', fontSize=22, textColor=WHITE,
                                              fontName='Helvetica-Bold', spaceAfter=2)))
    elements.append(Spacer(1, 14*mm))

    # ── Info Box ──────────────────────────────────────────────
    def info_label(txt):
        return Paragraph(f'<font color="#64748b">{txt}</font>',
                         ParagraphStyle('IL', fontSize=8, fontName='Helvetica-Bold', leading=12))
    def info_val(txt):
        return Paragraph(f'<font color="#1e293b">{txt}</font>',
                         ParagraphStyle('IV', fontSize=8.5, fontName='Helvetica', leading=12))

    load_badge_color = '#ef4444' if load_time > 3000 else '#10b981'
    load_badge       = 'SLOW'    if load_time > 3000 else 'GOOD'
    fw_display       = 'Selenium + Cypress' if framework == 'Both' else framework

    info_data = [
        [info_label('URL'),       info_val(url)],
        [info_label('Framework'), info_val(fw_display)],
        [info_label('Load Time'), Paragraph(
            f'<font color="#1e293b">{load_time} ms</font>  '
            f'<font color="{load_badge_color}"><b>● {load_badge}</b></font>',
            ParagraphStyle('LT', fontSize=8.5, fontName='Helvetica', leading=12))],
        [info_label('Page Type'), info_val('SPA (React/Vue/Angular)' if is_spa else 'Standard HTML')],
        [info_label('Generated'), info_val(datetime.now().strftime('%Y-%m-%d  %H:%M'))],
    ]
    info_tbl = Table(info_data, colWidths=[32*mm, 136*mm])
    info_tbl.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (0,-1), LIGHT_BG),
        ('FONTSIZE',      (0,0), (-1,-1), 8.5),
        ('PADDING',       (0,0), (-1,-1), 7),
        ('LINEBELOW',     (0,0), (-1,-2), 0.4, BORDER),
        ('BOX',           (0,0), (-1,-1), 0.8, BORDER_DARK),
        ('ROWBACKGROUNDS',(0,0), (-1,-1), [WHITE, LIGHT_BG]),
        ('LEFTPADDING',   (0,0), (0,-1), 10),
        ('VALIGN',        (0,0), (-1,-1), 'MIDDLE'),
    ]))
    elements.append(info_tbl)
    elements.append(Spacer(1, 20))

    # ── Légende priority/category ─────────────────────────────
    legend_items = [
        ('<b>Priority:</b>', ''),
        ('HIGH', '#ef4444'), ('MEDIUM', '#f59e0b'), ('LOW', '#10b981'),
        ('  |  <b>Category:</b>', ''),
        ('FUNCTIONAL', '#3b82f6'), ('PERFORMANCE', '#8b5cf6'),
        ('UI', '#ec4899'), ('NAVIGATION', '#10b981'),
    ]
    legend_parts = []
    for label, color in legend_items:
        if color:
            legend_parts.append(f'<font color="{color}"><b>{label}</b></font>')
        else:
            legend_parts.append(f'<font color="#64748b">{label}</font>')

    elements.append(Paragraph(
        '  '.join(legend_parts),
        ParagraphStyle('Legend', fontSize=7, fontName='Helvetica', leading=10,
                       textColor=HexColor('#64748b'))
    ))
    elements.append(Spacer(1, 10))

    # ── Sections principale ───────────────────────────────────
    if framework == 'Both':
        elements.append(framework_banner('  SELENIUM', SELENIUM_COLOR, SELENIUM_BG))
        elements.append(Spacer(1, 10))
        elements.append(section_header('📊', 'Test Summary — Selenium'))
        elements.append(Spacer(1, 8))
        build_stats_section(elements, test_cases_selenium, execution_results)
        elements.append(Spacer(1, 18))
        elements.append(section_header('🧪', 'Test Cases — Selenium'))
        elements.append(Spacer(1, 8))
        build_test_cases_table(elements, test_cases_selenium, execution_results)
        build_script_section(elements, script_selenium, 'Selenium')
        elements.append(Spacer(1, 30))
        elements.append(framework_banner('  CYPRESS', CYPRESS_COLOR, CYPRESS_BG))
        elements.append(Spacer(1, 10))
        elements.append(section_header('📊', 'Test Summary — Cypress'))
        elements.append(Spacer(1, 8))
        build_stats_section(elements, test_cases_cypress, [])
        elements.append(Spacer(1, 18))
        elements.append(section_header('🧪', 'Test Cases — Cypress'))
        elements.append(Spacer(1, 8))
        build_test_cases_table(elements, test_cases_cypress, [])
        build_script_section(elements, script_cypress, 'Cypress')
    else:
        elements.append(section_header('📊', 'Test Summary'))
        elements.append(Spacer(1, 8))
        build_stats_section(elements, test_cases, execution_results)
        elements.append(Spacer(1, 22))
        elements.append(section_header('🧪', 'Test Cases'))
        elements.append(Spacer(1, 8))
        build_test_cases_table(elements, test_cases, execution_results)
        build_script_section(elements, script, framework)

    elements.append(Spacer(1, 20))
    doc.build(elements, onFirstPage=on_page, onLaterPages=on_page)
    return buffer.getvalue()