from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor, white, black
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable, KeepTogether
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.platypus import Flowable
from io import BytesIO
from datetime import datetime

# ── Color Palette ──────────────────────────────────────────────
NAVY        = HexColor('#0a0f1e')
GOLD        = HexColor('#c9a227')
GREEN       = HexColor('#10b981')
GREEN_BG    = HexColor('#d1fae5')
RED         = HexColor('#ef4444')
RED_BG      = HexColor('#fee2e2')
ORANGE      = HexColor('#f59e0b')
ORANGE_BG   = HexColor('#fef3c7')
BLUE        = HexColor('#3b82f6')
BLUE_BG     = HexColor('#dbeafe')
LIGHT_BG    = HexColor('#f8fafc')
BORDER      = HexColor('#e2e8f0')
BORDER_DARK = HexColor('#cbd5e1')
MUTED       = HexColor('#94a3b8')
DARK_TEXT   = HexColor('#1e293b')
WHITE       = white

SELENIUM_COLOR = HexColor('#43a047')
SELENIUM_BG    = HexColor('#e8f5e9')
CYPRESS_COLOR  = HexColor('#1565c0')
CYPRESS_BG     = HexColor('#e3f2fd')

# ── Page decorations ───────────────────────────────────────────
def on_page(canvas, doc):
    W, H = A4
    canvas.saveState()
    canvas.setFillColor(NAVY)
    canvas.rect(0, H - 52*mm, W, 52*mm, fill=1, stroke=0)
    canvas.setFillColor(GOLD)
    canvas.rect(0, H - 54*mm, W, 2*mm, fill=1, stroke=0)
    canvas.setFillColor(GOLD)
    canvas.rect(0, 0, 3, H - 54*mm, fill=1, stroke=0)
    canvas.setFillColor(LIGHT_BG)
    canvas.rect(0, 0, W, 14*mm, fill=1, stroke=0)
    canvas.setFillColor(BORDER)
    canvas.rect(0, 14*mm, W, 0.5, fill=1, stroke=0)
    canvas.setFont('Helvetica', 7.5)
    canvas.setFillColor(MUTED)
    canvas.drawString(20*mm, 5*mm, 'Generated by NexTest — AI-Powered Test Automation Platform')
    canvas.drawRightString(W - 20*mm, 5*mm, f'Page {doc.page}  •  {datetime.now().strftime("%Y-%m-%d")}')
    canvas.restoreState()

# ── Reusable helpers ───────────────────────────────────────────
def section_header(emoji, text):
    data = [[Paragraph(f'{emoji}  {text}',
                       ParagraphStyle('SH', fontSize=11, fontName='Helvetica-Bold',
                                      textColor=DARK_TEXT, leading=14))]]
    tbl = Table(data, colWidths=[168*mm])
    tbl.setStyle(TableStyle([
        ('LINEBELOW',     (0,0), (-1,-1), 1.5, GOLD),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ('TOPPADDING',    (0,0), (-1,-1), 0),
    ]))
    return tbl

def framework_banner(label, color, bg):
    data = [[Paragraph(label, ParagraphStyle(
        'FB', fontSize=11, fontName='Helvetica-Bold', textColor=color, leading=14))]]
    tbl = Table(data, colWidths=[168*mm])
    tbl.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (-1,-1), bg),
        ('BOX',           (0,0), (-1,-1), 1, color),
        ('TOPPADDING',    (0,0), (-1,-1), 6),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ('LEFTPADDING',   (0,0), (-1,-1), 10),
    ]))
    return tbl

def stat_card(value, label, val_color, bg_color):
    inner = [[Paragraph(
        f'<font color="{val_color}"><b>{value}</b></font><br/>'
        f'<font color="#94a3b8" size="7"><b>{label}</b></font>',
        ParagraphStyle('SC', fontSize=18, fontName='Helvetica-Bold', alignment=TA_CENTER, leading=26))]]
    t = Table(inner, colWidths=[30*mm])
    t.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (-1,-1), bg_color),
        ('BOX',           (0,0), (-1,-1), 1, BORDER_DARK),
        ('TOPPADDING',    (0,0), (-1,-1), 12),
        ('BOTTOMPADDING', (0,0), (-1,-1), 12),
        ('ALIGN',         (0,0), (-1,-1), 'CENTER'),
    ]))
    return t

def build_stats_section(elements, test_cases):
    pass_count = sum(1 for t in test_cases if t.get('type') == 'positive')
    fail_count = sum(1 for t in test_cases if t.get('type') == 'negative')
    skip_count = len(test_cases) - pass_count - fail_count
    total      = len(test_cases)
    rate       = round((pass_count / total) * 100) if total > 0 else 0
    rate_hex   = '#10b981' if rate >= 80 else '#f59e0b' if rate >= 50 else '#ef4444'
    rate_bg    = GREEN_BG  if rate >= 80 else ORANGE_BG  if rate >= 50 else RED_BG

    stats_data = [[
        stat_card(pass_count, 'PASSED',    '#10b981', GREEN_BG),
        stat_card(fail_count, 'FAILED',    '#ef4444', RED_BG),
        stat_card(skip_count, 'SKIPPED',   '#f59e0b', ORANGE_BG),
        stat_card(f'{rate}%', 'PASS RATE', rate_hex,  rate_bg),
        stat_card(total,      'TOTAL',     '#3b82f6', BLUE_BG),
    ]]
    outer = Table(stats_data, colWidths=[33.6*mm]*5)
    outer.setStyle(TableStyle([
        ('ALIGN',   (0,0), (-1,-1), 'CENTER'),
        ('VALIGN',  (0,0), (-1,-1), 'MIDDLE'),
        ('PADDING', (0,0), (-1,-1), 2),
    ]))
    elements.append(outer)

def build_test_cases_table(elements, test_cases):
    col_w = [10*mm, 78*mm, 24*mm, 56*mm]
    header_row = [
        Paragraph('<font color="#ffffff"><b>#</b></font>',
                  ParagraphStyle('TH', fontSize=8.5, fontName='Helvetica-Bold', alignment=TA_CENTER)),
        Paragraph('<font color="#ffffff"><b>Test Name</b></font>',
                  ParagraphStyle('TH', fontSize=8.5, fontName='Helvetica-Bold')),
        Paragraph('<font color="#ffffff"><b>Type</b></font>',
                  ParagraphStyle('TH', fontSize=8.5, fontName='Helvetica-Bold', alignment=TA_CENTER)),
        Paragraph('<font color="#ffffff"><b>Expected Result</b></font>',
                  ParagraphStyle('TH', fontSize=8.5, fontName='Helvetica-Bold')),
    ]
    tc_rows = [header_row]
    for i, tc in enumerate(test_cases):
        tc_type = tc.get('type', 'positive')
        if tc_type == 'positive':
            type_color, type_label = '#10b981', '✓  PASS'
        elif tc_type == 'negative':
            type_color, type_label = '#ef4444', '✗  FAIL'
        else:
            type_color, type_label = '#f59e0b', '⚠  SKIP'

        desc      = tc.get('description', '')
        desc_short = desc[:70] + '…' if len(desc) > 70 else desc
        exp        = tc.get('expected', '')
        exp_short  = exp[:65] + '…' if len(exp) > 65 else exp

        tc_rows.append([
            Paragraph(f'<font color="#64748b"><b>{tc.get("id","")}</b></font>',
                      ParagraphStyle('IDC', fontSize=8.5, fontName='Helvetica-Bold', alignment=TA_CENTER)),
            Paragraph(
                f'<b><font color="#1e293b">{tc.get("name","")}</font></b><br/>'
                f'<font color="#94a3b8" size="7.5">{desc_short}</font>',
                ParagraphStyle('TCN', fontSize=9, fontName='Helvetica', leading=13)),
            Paragraph(
                f'<font color="{type_color}"><b>{type_label}</b></font>',
                ParagraphStyle('TYP', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
            Paragraph(
                f'<font color="#475569">{exp_short}</font>',
                ParagraphStyle('EXP', fontSize=8, fontName='Helvetica', leading=12)),
        ])

    tc_tbl = Table(tc_rows, colWidths=col_w, repeatRows=1)
    tc_tbl.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (-1,0), NAVY),
        ('TEXTCOLOR',     (0,0), (-1,0), WHITE),
        ('FONTNAME',      (0,0), (-1,0), 'Helvetica-Bold'),
        ('TOPPADDING',    (0,0), (-1,0), 9),
        ('BOTTOMPADDING', (0,0), (-1,0), 9),
        ('ROWBACKGROUNDS',(0,1), (-1,-1), [WHITE, LIGHT_BG]),
        ('PADDING',       (0,1), (-1,-1), 8),
        ('LINEBELOW',     (0,0), (-1,-1), 0.4, BORDER),
        ('BOX',           (0,0), (-1,-1), 0.8, BORDER_DARK),
        ('VALIGN',        (0,0), (-1,-1), 'MIDDLE'),
        ('ALIGN',         (0,0), (0,-1), 'CENTER'),
        ('ALIGN',         (2,0), (2,-1), 'CENTER'),
    ]))
    elements.append(tc_tbl)

def build_script_section(elements, script, framework_label):
    if not script:
        return
    elements.append(Spacer(1, 18))
    elements.append(section_header('📄', f'AI-Generated {framework_label} Script'))
    elements.append(Spacer(1, 4))
    elements.append(Paragraph(
        "<font color='#94a3b8'><i>Ce script a été généré automatiquement par l'IA pour tester votre site.</i></font>",
        ParagraphStyle('Info', fontSize=7.5, fontName='Helvetica')))
    elements.append(Spacer(1, 6))

    lines = script.replace('\\n', '\n').split('\n')[:60]
    code_rows = []
    for ln_no, line in enumerate(lines, 1):
        safe = line.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
        code_rows.append([
            Paragraph(f'<font color="#94a3b8">{ln_no}</font>',
                      ParagraphStyle('LN', fontSize=7, fontName='Courier', alignment=TA_RIGHT, leading=12)),
            Paragraph(safe or ' ',
                      ParagraphStyle('CL', fontSize=7.8, fontName='Courier',
                                     textColor=HexColor('#1e293b'), leading=12)),
        ])

    code_tbl = Table(code_rows, colWidths=[10*mm, 158*mm])
    code_tbl.setStyle(TableStyle([
        ('BACKGROUND',  (0,0), (-1,-1), HexColor('#f8fafc')),
        ('BACKGROUND',  (0,0), (0,-1),  HexColor('#f1f5f9')),
        ('PADDING',     (0,0), (-1,-1), 3),
        ('LEFTPADDING', (0,0), (0,-1),  6),
        ('RIGHTPADDING',(0,0), (0,-1),  6),
        ('LEFTPADDING', (1,0), (1,-1),  8),
        ('BOX',         (0,0), (-1,-1), 1, BORDER_DARK),
        ('LINEAFTER',   (0,0), (0,-1),  0.5, BORDER_DARK),
        ('VALIGN',      (0,0), (-1,-1), 'TOP'),
    ]))
    elements.append(code_tbl)

    if len(script.split('\n')) > 60:
        elements.append(Spacer(1, 4))
        elements.append(Paragraph(
            '<font color="#94a3b8"><i>… script truncated — download full version for complete output</i></font>',
            ParagraphStyle('Trunc', fontSize=7.5, fontName='Helvetica', alignment=TA_CENTER)))

# ── Main ───────────────────────────────────────────────────────
def generate_pdf(generation_data: dict) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                            rightMargin=20*mm, leftMargin=22*mm,
                            topMargin=58*mm, bottomMargin=20*mm)

    title_style = ParagraphStyle('Title', fontSize=22, textColor=WHITE,
                                  fontName='Helvetica-Bold', spaceAfter=2, alignment=TA_LEFT)

    url       = generation_data.get('url', '')
    framework = generation_data.get('framework', 'Selenium')  # 'Selenium' | 'Cypress' | 'Both'
    load_time = generation_data.get('load_time_ms', 0)
    is_spa    = generation_data.get('is_spa', False)

    test_cases          = generation_data.get('test_cases', [])
    test_cases_selenium = generation_data.get('test_cases_selenium', [])
    test_cases_cypress  = generation_data.get('test_cases_cypress', [])
    script              = generation_data.get('script', '')
    script_selenium     = generation_data.get('script_selenium', '')
    script_cypress      = generation_data.get('script_cypress', '')

    elements = []

    # ── Header ────────────────────────────────────────────────
    header_data = [[
        Paragraph('<font color="#c9a227"><b>NEX</b></font><font color="#ffffff">TEST</font>',
                  ParagraphStyle('Logo', fontSize=24, fontName='Helvetica-Bold')),
        Paragraph(f'<font color="#64748b">Generated</font><br/>'
                  f'<font color="#94a3b8">{datetime.now().strftime("%B %d, %Y  •  %H:%M")}</font>',
                  ParagraphStyle('Date', fontSize=8.5, fontName='Helvetica', alignment=TA_RIGHT, leading=13))
    ]]
    header_tbl = Table(header_data, colWidths=[90*mm, 78*mm])
    header_tbl.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('TOPPADDING', (0,0), (-1,-1), 0),
        ('BOTTOMPADDING', (0,0), (-1,-1), 0),
    ]))
    elements.append(Spacer(1, -38*mm))
    elements.append(header_tbl)
    elements.append(Spacer(1, 6*mm))
    elements.append(Paragraph('Test Automation Report', title_style))
    elements.append(Spacer(1, 14*mm))

    # ── Info Box ──────────────────────────────────────────────
    def info_label(txt):
        return Paragraph(f'<font color="#64748b">{txt}</font>',
                         ParagraphStyle('IL', fontSize=8, fontName='Helvetica-Bold', leading=12))
    def info_val(txt):
        return Paragraph(f'<font color="#1e293b">{txt}</font>',
                         ParagraphStyle('IV', fontSize=8.5, fontName='Helvetica', leading=12))

    load_badge_color = '#ef4444' if load_time > 3000 else '#10b981'
    load_badge       = 'SLOW' if load_time > 3000 else 'GOOD'
    fw_display       = 'Selenium + Cypress' if framework == 'Both' else framework

    info_data = [
        [info_label('URL'),       info_val(url)],
        [info_label('Framework'), info_val(fw_display)],
        [info_label('Load Time'), Paragraph(
            f'<font color="#1e293b">{load_time} ms</font>  '
            f'<font color="{load_badge_color}"><b>● {load_badge}</b></font>',
            ParagraphStyle('LT', fontSize=8.5, fontName='Helvetica', leading=12))],
        [info_label('Page Type'), info_val('SPA (React/Vue/Angular)' if is_spa else 'Standard HTML')],
        [info_label('Generated'), info_val(datetime.now().strftime('%Y-%m-%d  %H:%M'))],
    ]
    info_tbl = Table(info_data, colWidths=[32*mm, 136*mm])
    info_tbl.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (0,-1), LIGHT_BG),
        ('FONTSIZE',      (0,0), (-1,-1), 8.5),
        ('PADDING',       (0,0), (-1,-1), 7),
        ('LINEBELOW',     (0,0), (-1,-2), 0.4, BORDER),
        ('BOX',           (0,0), (-1,-1), 0.8, BORDER_DARK),
        ('ROWBACKGROUNDS',(0,0), (-1,-1), [WHITE, LIGHT_BG]),
        ('LEFTPADDING',   (0,0), (0,-1), 10),
        ('VALIGN',        (0,0), (-1,-1), 'MIDDLE'),
    ]))
    elements.append(info_tbl)
    elements.append(Spacer(1, 20))

    # ══════════════════════════════════════════════════════════
    # CASE 1 : Both → deux sections séparées Selenium + Cypress
    # ══════════════════════════════════════════════════════════
    if framework == 'Both':

        # ── SELENIUM ──────────────────────────────────────────
        elements.append(framework_banner('🟢  SELENIUM', SELENIUM_COLOR, SELENIUM_BG))
        elements.append(Spacer(1, 10))
        elements.append(section_header('📊', 'Test Summary — Selenium'))
        elements.append(Spacer(1, 8))
        build_stats_section(elements, test_cases_selenium)
        elements.append(Spacer(1, 18))
        elements.append(section_header('🧪', 'Test Cases — Selenium'))
        elements.append(Spacer(1, 8))
        build_test_cases_table(elements, test_cases_selenium)
        build_script_section(elements, script_selenium, 'Selenium')

        elements.append(Spacer(1, 30))

        # ── CYPRESS ───────────────────────────────────────────
        elements.append(framework_banner('🔵  CYPRESS', CYPRESS_COLOR, CYPRESS_BG))
        elements.append(Spacer(1, 10))
        elements.append(section_header('📊', 'Test Summary — Cypress'))
        elements.append(Spacer(1, 8))
        build_stats_section(elements, test_cases_cypress)
        elements.append(Spacer(1, 18))
        elements.append(section_header('🧪', 'Test Cases — Cypress'))
        elements.append(Spacer(1, 8))
        build_test_cases_table(elements, test_cases_cypress)
        build_script_section(elements, script_cypress, 'Cypress')

    # ══════════════════════════════════════════════════════════
    # CASE 2 : Selenium ou Cypress → une seule section
    # ══════════════════════════════════════════════════════════
    else:
        elements.append(section_header('📊', 'Test Summary'))
        elements.append(Spacer(1, 8))
        build_stats_section(elements, test_cases)
        elements.append(Spacer(1, 22))
        elements.append(section_header('🧪', 'Test Cases'))
        elements.append(Spacer(1, 8))
        build_test_cases_table(elements, test_cases)
        build_script_section(elements, script, framework)

    elements.append(Spacer(1, 20))
    doc.build(elements, onFirstPage=on_page, onLaterPages=on_page)
    return buffer.getvalue()


# ── Demo ──────────────────────────────────────────────────────
if __name__ == '__main__':
    sample = {
        'url': 'https://www.netflix.com/tn-fr/',
        'framework': 'Both',
        'load_time_ms': 4207,
        'is_spa': False,
        'test_cases': [],
        'test_cases_selenium': [
            {'id':1,'name':'Happy Path Test','type':'positive','description':'Verifies that the user can successfully navigate to the login page','expected':'The user is redirected to the next page'},
            {'id':2,'name':'Invalid Email Test','type':'negative','description':'Verifies that the form does not submit with an invalid email address','expected':'An error message is displayed'},
            {'id':3,'name':'Empty Email Field Test','type':'negative','description':'Verifies that the form does not submit with an empty email field','expected':'An error message is displayed'},
            {'id':4,'name':'Language Select Test','type':'positive','description':'Verifies that the language select dropdown is functional','expected':'The language is changed successfully'},
            {'id':5,'name':'Performance Test','type':'positive','description':'Verifies that the page load time is within the acceptable range','expected':'The page load time is less than 3000ms'},
        ],
        'test_cases_cypress': [
            {'id':1,'name':'Happy Path Test','type':'positive','description':'Verifies that the user can successfully navigate to the login page','expected':'The user is redirected to the next page'},
            {'id':2,'name':'Invalid Email Test','type':'negative','description':'Verifies that the form does not submit with an invalid email address','expected':'An error message is displayed'},
            {'id':3,'name':'Navigation Test','type':'positive','description':'Verifies that the navigation links are functional','expected':'The user is redirected to the login page'},
            {'id':4,'name':'Image Loading Test','type':'positive','description':'Verifies that the images on the page are loaded successfully','expected':'All images are loaded successfully'},
        ],
        'script': '',
        'script_selenium': """from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

driver = webdriver.Chrome()
driver.get('https://www.netflix.com/tn-fr/')

def test_happy_path():
    email_input = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.ID, ':r0:')))
    email_input.send_keys('test@example.com')

def test_invalid_email():
    email_input = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.ID, ':r0:')))
    email_input.send_keys('invalid_email')

test_happy_path()
test_invalid_email()
driver.quit()""",
        'script_cypress': """describe('Netflix Tests', () => {
  beforeEach(() => {
    cy.visit('https://www.netflix.com/tn-fr/')
  })

  it('Happy Path Test', () => {
    cy.get('#\\:r0\\:').type('test@example.com')
    cy.contains('button', 'Commencer').click()
  })

  it('Invalid Email Test', () => {
    cy.get('#\\:r0\\:').type('invalid_email')
    cy.contains('button', 'Commencer').click()
    cy.get('.grecaptcha-error').should('be.visible')
  })
})""",
    }

    pdf_bytes = generate_pdf(sample)
    with open('/mnt/user-data/outputs/nextest_report_improved.pdf', 'wb') as f:
        f.write(pdf_bytes)
    print('Done!')