# security_runner.py — NexTest Security Test Runner
# Executes security test cases generated by security_generator.py

import requests
import time
import json
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)


def _get_nested(obj, path):
    """Navigate nested dict with dot notation: 'data.token'"""
    keys = path.split(".")
    for key in keys:
        if isinstance(obj, dict):
            obj = obj.get(key)
        else:
            return None
    return obj


def _run_one_security(tc: dict, token: str) -> dict:
    """Execute a single security test case"""

    url         = tc.get("url", "")
    method      = tc.get("method", "GET").upper()
    body        = tc.get("body")
    headers     = dict(tc.get("headers", {}))
    expect      = tc.get("expect_status")
    repeat      = tc.get("repeat", 1)
    expect_blocked      = tc.get("expect_blocked", False)
    check_headers       = tc.get("check_headers", [])
    forbidden_in_resp   = tc.get("forbidden_in_response", [])
    category    = tc.get("category", "")
    severity    = tc.get("severity", "medium")

    # Accept list or int for expect_status
    if isinstance(expect, int):
        expected_statuses = [expect]
    else:
        expected_statuses = list(expect)

    start        = time.time()
    final_status = "fail"
    reason       = ""
    last_code    = None
    responses    = []

    try:
        for attempt in range(repeat):
            if method == "GET":
                resp = requests.get(url, headers=headers, verify=False, timeout=10)
            elif method == "POST":
                resp = requests.post(url, json=body, headers=headers, verify=False, timeout=10)
            elif method == "DELETE":
                resp = requests.delete(url, headers=headers, verify=False, timeout=10)
            else:
                resp = requests.request(method, url, json=body, headers=headers, verify=False, timeout=10)

            last_code = resp.status_code
            responses.append(resp)

            # Small delay between repeated requests
            if repeat > 1 and attempt < repeat - 1:
                time.sleep(0.1)

    except Exception as e:
        duration_ms = int((time.time() - start) * 1000)
        return {
            "id":          tc.get("id"),
            "name":        tc.get("name"),
            "category":    category,
            "severity":    severity,
            "method":      method,
            "url":         url,
            "status":      "fail",
            "reason":      f"Request error: {str(e)}",
            "duration":    f"{duration_ms}ms",
            "status_code": None,
            "description": tc.get("description", ""),
        }

    duration_ms = int((time.time() - start) * 1000)
    last_resp   = responses[-1]

    try:
        resp_json = last_resp.json()
        resp_text = json.dumps(resp_json).lower()
    except Exception:
        resp_json = {}
        resp_text = last_resp.text.lower()

    # ── Rate limiting check ──────────────────────────────────────────────────
    if category == "rate_limiting" and expect_blocked:
        blocked = any(r.status_code == 429 for r in responses)
        all_rejected = all(r.status_code in expected_statuses for r in responses)

        if blocked:
            final_status = "pass"
            reason = f"Rate limiting active — got 429 after {repeat} requests ✓"
        elif all_rejected:
            # Server rejects all but doesn't rate-limit → warn
            final_status = "warn"
            reason = (
                f"All {repeat} requests returned {last_code} (rejected) "
                f"but no 429 rate-limit detected — consider adding rate limiting"
            )
        else:
            final_status = "fail"
            reason = f"No rate limiting detected after {repeat} requests — last status: {last_code}"

    # ── Security headers check ───────────────────────────────────────────────
    elif check_headers:
        status_ok   = last_code in expected_statuses
        missing_hdrs = [h for h in check_headers if h.lower() not in {k.lower() for k in last_resp.headers}]

        if status_ok and not missing_hdrs:
            final_status = "pass"
            reason = f"HTTP {last_code} ✓ | All security headers present ✓"
        elif status_ok and missing_hdrs:
            final_status = "warn"
            reason = f"HTTP {last_code} ✓ | Missing headers: {', '.join(missing_hdrs)}"
        else:
            final_status = "fail"
            reason = f"Expected status {expected_statuses}, got {last_code}"

    # ── Forbidden content in response ────────────────────────────────────────
    elif forbidden_in_resp:
        status_ok = last_code in expected_statuses
        leaks     = [w for w in forbidden_in_resp if w.lower() in resp_text]

        if status_ok and not leaks:
            final_status = "pass"
            reason = f"HTTP {last_code} ✓ | No sensitive data leaked ✓"
        elif leaks:
            final_status = "fail"
            reason = f"Sensitive data leaked in response: {', '.join(leaks)}"
        else:
            final_status = "fail"
            reason = f"Expected status {expected_statuses}, got {last_code}"

    # ── Auth check ───────────────────────────────────────────────────────────
    elif category == "auth":
        if last_code in [401, 403]:
            final_status = "pass"
            reason = f"HTTP {last_code} ✓ | Endpoint correctly rejects unauthenticated requests ✓"
        elif last_code == 500:
            final_status = "fail"
            reason = f"HTTP 500 — server CRASHES without token! Should return 401. Critical vulnerability!"
        elif last_code == 405:
            final_status = "warn"
            reason = f"HTTP 405 — wrong method used"
        elif last_code == 200:
            final_status = "fail"
            reason = f"HTTP 200 — endpoint accessible WITHOUT token! Critical vulnerability!"
        else:
            final_status = "pass"
            reason = f"HTTP {last_code} ✓ | Request rejected ✓"

    # ── Input validation check ───────────────────────────────────────────────
    elif category == "input_validation":
        if last_code in [400, 422]:
            final_status = "pass"
            reason = f"HTTP {last_code} ✓ | Malicious input correctly rejected ✓"
        elif last_code == 500:
            final_status = "fail"
            reason = f"HTTP 500 — server CRASHED on malicious input! Potential injection vulnerability!"
        elif last_code == 200:
            final_status = "fail"
            reason = f"HTTP 200 — malicious input was ACCEPTED! Potential injection vulnerability!"
        else:
            final_status = "warn"
            reason = f"HTTP {last_code} — unexpected response to malicious input"

    # ── Headers check ────────────────────────────────────────────────────────
    elif check_headers:
        if last_code == 405:
            final_status = "warn"
            reason = f"HTTP 405 — wrong method, can't check headers"
        elif last_code == 500:
            final_status = "warn"
            reason = f"HTTP 500 — server error, headers check skipped"
        else:
            missing_hdrs = [h for h in check_headers if h.lower() not in {k.lower() for k in last_resp.headers}]
            if not missing_hdrs:
                final_status = "pass"
                reason = f"HTTP {last_code} ✓ | All security headers present ✓"
            else:
                final_status = "warn"
                reason = f"HTTP {last_code} | Missing security headers: {', '.join(missing_hdrs)}"

    # ── Standard status check (fallback) ────────────────────────────────────
    else:
        if last_code == 405:
            final_status = "warn"
            reason = f"HTTP 405 — endpoint exists but wrong HTTP method used"
        elif last_code == 500:
            final_status = "warn"
            reason = f"HTTP 500 — server error"
        elif last_code in expected_statuses:
            final_status = "pass"
            reason = f"HTTP {last_code} ✓ | {duration_ms}ms | Expected response ✓"
        else:
            final_status = "fail"
            reason = f"Expected {expected_statuses}, got {last_code} — potential vulnerability!"

    return {
        "id":          tc.get("id"),
        "name":        tc.get("name"),
        "category":    category,
        "severity":    severity,
        "method":      method,
        "url":         url,
        "status":      final_status,
        "reason":      reason,
        "duration":    f"{duration_ms}ms",
        "status_code": last_code,
        "description": tc.get("description", ""),
        "repeat":      repeat,
    }


def run_security_tests(test_cases: list, token: str = "") -> dict:
    """Run all security test cases and return results"""

    print(f"[SECURITY_RUNNER] Running {len(test_cases)} security tests")

    results = []
    for i, tc in enumerate(test_cases, 1):
        print(f"[SECURITY_RUNNER] [{i}/{len(test_cases)}] {tc.get('severity','?').upper()} | {tc.get('name','')}")
        result = _run_one_security(tc, token)
        results.append(result)
        print(f"[SECURITY_RUNNER]   → {result['status'].upper()} | {result['reason'][:80]}")

    pass_count = sum(1 for r in results if r["status"] == "pass")
    warn_count = sum(1 for r in results if r["status"] == "warn")
    fail_count = sum(1 for r in results if r["status"] == "fail")
    executed   = pass_count + fail_count + warn_count
    pass_rate  = round(pass_count / executed * 100) if executed else 0

    print(f"[SECURITY_RUNNER] DONE | {pass_count} pass / {warn_count} warn / {fail_count} fail | {pass_rate}%")

    return {
        "results":    results,
        "pass_count": pass_count,
        "warn_count": warn_count,
        "fail_count": fail_count,
        "pass_rate":  pass_rate,
        "total":      len(results),
    }