from matplotlib.pyplot import rc
from numpy import fix
import platform
from urllib.parse import urlparse
from reportlab.platypus import Image
from PIL import Image as PILImage
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.colors import HexColor, white
from reportlab.lib.units import mm
from reportlab.lib.enums import TA_CENTER, TA_RIGHT

from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable, KeepTogether, PageBreak
)
from io import BytesIO
from datetime import datetime
import base64

from xml.sax.saxutils import escape as _xml_escape

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from openpyxl.chart import BarChart, Reference



def _esc(text):
    """Escape HTML/XML special chars so ReportLab doesn't try to parse them as tags."""
    if not isinstance(text, str):
        return text
    return _xml_escape(text)

#Color Palette
NAVY        = HexColor('#0a0f1e')
GREEN       = HexColor('#10b981')
GREEN_BG    = HexColor('#d1fae5')
RED         = HexColor('#ef4444')
RED_BG      = HexColor('#fee2e2')
ORANGE      = HexColor('#f59e0b')
ORANGE_BG   = HexColor('#fef3c7')
BLUE        = HexColor('#3b82f6')
BLUE_BG     = HexColor('#dbeafe')
LIGHT_BG    = HexColor('#f8fafc')
BORDER      = HexColor('#e2e8f0')
BORDER_DARK = HexColor('#cbd5e1')
MUTED       = HexColor('#94a3b8')
DARK_TEXT   = HexColor('#1e293b')
WHITE       = white
INDIGO      = HexColor('#4f46e5')
INDIGO_BG   = HexColor('#e0e7ff')
TEAL        = HexColor('#0d9488')
TEAL_BG     = HexColor('#ccfbf1')
SEO_GREEN   = HexColor('#16a34a')   # accent couleur SEO
SEO_BG      = HexColor('#dcfce7')

#Category colors
CAT_COLORS = {
    'security':      '#ef4444',
    'accessibility': '#8b5cf6',
    'meta':          '#3b82f6',
    'structure':     '#f97316',
    'mobile':        '#0ea5e9',
    'technical':     '#6366f1',
    'social':        '#ec4899',
    'content':       '#10b981',
    'performance':   '#f59e0b',
}

PRIORITY_COLORS = {
    'high':   '#ef4444',
    'medium': '#f59e0b',
    'low':    '#10b981',
}


#Helpers
def _ps(name, **kwargs):
    return ParagraphStyle(name, **kwargs)


def _p(html, style):
    return Paragraph(html, style)


def _decode_screenshot(raw):
    """Accepts either raw PNG bytes (internal calls) or a base64 string
    (as received over the /generate-pdf JSON endpoint) and returns bytes or None."""
    if not raw:
        return None
    if isinstance(raw, (bytes, bytearray)):
        return bytes(raw)
    if isinstance(raw, str):
        try:
            return base64.b64decode(raw)
        except Exception as e:
            print(f"[SEO PDF] Failed to decode screenshot base64: {e}")
            return None
    return None


def on_page_seo(canvas, doc):
    W, H = A4
    canvas.saveState()
    canvas.setFillColor(NAVY)
    canvas.rect(0, H - 52*mm, W, 52*mm, fill=1, stroke=0)
    canvas.setFillColor(SEO_GREEN)
    canvas.rect(0, H - 54*mm, W, 2*mm, fill=1, stroke=0)
    canvas.setFillColor(SEO_GREEN)
    canvas.rect(0, 0, 3, H - 54*mm, fill=1, stroke=0)
    canvas.setFillColor(LIGHT_BG)
    canvas.rect(0, 0, W, 14*mm, fill=1, stroke=0)
    canvas.setFillColor(BORDER)
    canvas.rect(0, 14*mm, W, 0.5, fill=1, stroke=0)
    canvas.setFont('Helvetica', 7.5)
    canvas.setFillColor(MUTED)
    canvas.drawString(20*mm, 5*mm, 'Generated by NexTest — SEO Test Report')
    canvas.drawRightString(W - 20*mm, 5*mm,
        f'Page {doc.page}  •  {datetime.now().strftime("%Y-%m-%d")}')
    canvas.restoreState()


def _section_header(text, color=None):
    accent = HexColor(color) if isinstance(color, str) else (color or SEO_GREEN)
    tbl = Table([[_p(f'<b>{text}</b>',
        _ps('SH', fontSize=11, fontName='Helvetica-Bold',
            textColor=DARK_TEXT, leading=14))
    ]], colWidths=[168*mm])
    tbl.setStyle(TableStyle([
        ('LINEBELOW',     (0,0), (-1,-1), 1.5, accent),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ('TOPPADDING',    (0,0), (-1,-1), 0),
    ]))
    return tbl


def _stat_card(value, label, val_color, bg_color):
    inner = [[_p(
        f'<font color="{val_color}"><b>{value}</b></font><br/>'
        f'<font color="#94a3b8" size="7"><b>{label}</b></font>',
        _ps('SC', fontSize=18, fontName='Helvetica-Bold',
            alignment=TA_CENTER, leading=26))]]
    t = Table(inner, colWidths=[30*mm])
    t.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (-1,-1), bg_color),
        ('BOX',           (0,0), (-1,-1), 1, BORDER_DARK),
        ('TOPPADDING',    (0,0), (-1,-1), 12),
        ('BOTTOMPADDING', (0,0), (-1,-1), 12),
        ('ALIGN',         (0,0), (-1,-1), 'CENTER'),
    ]))
    return t


#SECTION 1 — SEO Scenarios (planned checks)
def _build_seo_scenarios(elements, test_cases, url):
    elements.append(_section_header('SEO Test Scenarios', '#16a34a'))
    elements.append(Spacer(1, 4))
    elements.append(_p(
        f'<font color="#64748b" size="7.5"><i>'
        f'17 SEO checks planned for <b>{url}</b> — '
        f'analyzed with a headless Chromium browser (Playwright) for full rendering.'
        f'</i></font>',
        _ps('ScInfo', fontSize=7.5, fontName='Helvetica', leading=10)))
    elements.append(Spacer(1, 8))

    EXPECTED_MAP = {
        'HTTPS Enabled':                    'Site must be served over HTTPS',
        'Page Accessible':                  'Page must return HTTP 200',
        'Title Tag Present':                'A &lt;title&gt; tag must exist',
        'Title Length Optimal':             'Title length must be between 30–60 characters',
        'Meta Description Present':         'A meta description tag must exist',
        'Meta Description Length Optimal':  'Meta description must be between 70–160 characters',
        'Single H1 Tag':                    'Exactly one &lt;h1&gt; tag must be present',
        'H2 Tags Present':                  'At least one &lt;h2&gt; tag should exist',
        'All Images Have Alt Text':         'Every &lt;img&gt; must have a non-empty alt attribute',
        'Viewport Meta Tag':                'A responsive viewport meta tag must be present',
        'Canonical URL Defined':            'A canonical &lt;link&gt; tag must be defined',
        'Open Graph Tags Present':          'og:title and og:description must be present',
        'Schema Markup Present':            'Structured data (JSON-LD) should be present',
        'robots.txt Found':                 'A valid /robots.txt must exist',
        'sitemap.xml Found':                'A valid /sitemap.xml must exist',
        'Sufficient Word Count':            'Page must contain at least 300 words',
        'Fast Page Load (<3000ms)':         'Page must load in under 3000ms',
}

    hdr = [
        _p('<font color="#ffffff"><b>#</b></font>',
           _ps('H0', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
        _p('<font color="#ffffff"><b>SEO Check</b></font>',
           _ps('H1', fontSize=8, fontName='Helvetica-Bold')),
        _p('<font color="#ffffff"><b>Category</b></font>',
           _ps('H2', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
        _p('<font color="#ffffff"><b>Expected Result</b></font>',
           _ps('H3', fontSize=8, fontName='Helvetica-Bold')),
        _p('<font color="#ffffff"><b>Impact</b></font>',
           _ps('H4', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
    ]
    rows = [hdr]
    row_styles = []

    IMPACT_MAP = {
        'security': 'HIGH', 'technical': 'HIGH',
        'meta': 'HIGH', 'accessibility': 'HIGH',
        'structure': 'MEDIUM', 'mobile': 'MEDIUM',
        'content': 'MEDIUM', 'performance': 'MEDIUM',
        'social': 'LOW',
    }
    IMPACT_COLORS = {'HIGH': '#ef4444', 'MEDIUM': '#f59e0b', 'LOW': '#10b981'}

    for i, tc in enumerate(test_cases):
        cat     = tc.get('category', 'technical')
        cc      = CAT_COLORS.get(cat, '#64748b')
        impact  = IMPACT_MAP.get(cat, 'MEDIUM')
        ic      = IMPACT_COLORS.get(impact, '#f59e0b')
        expected = EXPECTED_MAP.get(tc['name'], 'Check passes successfully')

        rows.append([
            _p(f'<font color="#64748b"><b>{i+1}</b></font>',
               _ps(f'SID{i}', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
            _p(f'<b><font color="#1e293b" size="8">{tc["name"]}</font></b>',
               _ps(f'SN{i}', fontSize=8, fontName='Helvetica', leading=11)),
            _p(f'<font color="{cc}"><b>{cat.upper()}</b></font>',
               _ps(f'SC{i}', fontSize=7, fontName='Helvetica-Bold', alignment=TA_CENTER)),
            _p(f'<font color="#475569" size="7">{expected}</font>',
               _ps(f'SE{i}', fontSize=7, fontName='Helvetica', leading=10)),
            _p(f'<font color="{ic}"><b>{impact}</b></font>',
               _ps(f'SI{i}', fontSize=7, fontName='Helvetica-Bold', alignment=TA_CENTER)),
        ])
        if i % 2 == 1:
            row_styles.append(('BACKGROUND', (0, i+1), (-1, i+1), LIGHT_BG))

    tbl = Table(rows, colWidths=[8*mm, 60*mm, 24*mm, 58*mm, 18*mm], repeatRows=1)
    tbl.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (-1,0), NAVY),
        ('PADDING',       (0,0), (-1,-1), 7),
        ('LINEBELOW',     (0,0), (-1,-1), 0.4, BORDER),
        ('BOX',           (0,0), (-1,-1), 0.8, SEO_GREEN),
        ('VALIGN',        (0,0), (-1,-1), 'TOP'),
        ('ALIGN',         (0,0), (0,-1), 'CENTER'),
        ('ALIGN',         (2,0), (2,-1), 'CENTER'),
        ('ALIGN',         (4,0), (4,-1), 'CENTER'),
        ('LINEBEFORE',    (2,1), (2,-1), 1, BORDER),
        ('LINEBEFORE',    (4,1), (4,-1), 1, BORDER),
    ] + row_styles))
    elements.append(tbl)
    elements.append(Spacer(1, 16))


#SECTION 2 — Results by Category
def _build_category_summary(elements, test_cases):
    elements.append(Spacer(1, 8))
    elements.append(_section_header('Results by Category', '#16a34a'))
    elements.append(Spacer(1, 8))

    cats = {}
    for tc in test_cases:
        cat = tc.get('category', 'technical')
        if cat not in cats:
            cats[cat] = {'pass': 0, 'fail': 0, 'total': 0}
        cats[cat]['total'] += 1
        if tc.get('status') == 'pass':
            cats[cat]['pass'] += 1
        else:
            cats[cat]['fail'] += 1

    hdr = [
        _p('<font color="#ffffff"><b>Category</b></font>',
           _ps('CCH1', fontSize=8, fontName='Helvetica-Bold')),
        _p('<font color="#ffffff"><b>Total</b></font>',
           _ps('CCH2', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
        _p('<font color="#ffffff"><b>Passed</b></font>',
           _ps('CCH3', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
        _p('<font color="#ffffff"><b>Failed</b></font>',
           _ps('CCH4', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
        _p('<font color="#ffffff"><b>Pass Rate</b></font>',
           _ps('CCH5', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
        _p('<font color="#ffffff"><b>Verdict</b></font>',
           _ps('CCH6', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
    ]
    rows = [hdr]
    row_styles = []

    for cat, data in cats.items():
        cc      = CAT_COLORS.get(cat, '#64748b')
        rate    = round(data['pass'] / data['total'] * 100) if data['total'] > 0 else 0
        rc      = '#10b981' if rate == 100 else '#f59e0b' if rate >= 50 else '#ef4444'
        verdict = 'PASS' if data['fail'] == 0 else 'FAIL'
        vc      = '#10b981' if data['fail'] == 0 else '#ef4444'
        row_bg  = HexColor('#f0fdf4') if data['fail'] == 0 else HexColor('#fef2f2')

        rows.append([
            _p(f'<font color="{cc}"><b>{cat.upper()}</b></font>',
               _ps(f'CC{cat}', fontSize=8, fontName='Helvetica-Bold')),
            _p(f'<font color="#1e293b"><b>{data["total"]}</b></font>',
               _ps(f'CT{cat}', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
            _p(f'<font color="#10b981"><b>{data["pass"]}</b></font>',
               _ps(f'CP{cat}', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
            _p(f'<font color="#ef4444"><b>{data["fail"]}</b></font>',
               _ps(f'CF{cat}', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
            _p(f'<font color="{rc}"><b>{rate}%</b></font>',
               _ps(f'CR{cat}', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
            _p(f'<font color="{vc}"><b>{verdict}</b></font>',
               _ps(f'CV{cat}', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
        ])
        ri = len(rows) - 1
        row_styles.append(('BACKGROUND', (0, ri), (-1, ri), row_bg))

    tbl = Table(rows, colWidths=[34*mm, 16*mm, 18*mm, 18*mm, 22*mm, 60*mm], repeatRows=1)
    tbl.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), NAVY),
        ('PADDING',    (0,0), (-1,-1), 8),
        ('LINEBELOW',  (0,0), (-1,-1), 0.4, BORDER),
        ('BOX',        (0,0), (-1,-1), 0.8, SEO_GREEN),
        ('VALIGN',     (0,0), (-1,-1), 'MIDDLE'),
        ('ALIGN',      (1,0), (5,-1), 'CENTER'),
    ] + row_styles))
    elements.append(tbl)
    elements.append(Spacer(1, 16))

#SECTION 2bis — Severity Legend
def _build_severity_legend(elements):
    elements.append(_p(
        '<font color="#1e293b" size="8"><b>Severity Legend: </b></font>'
        '<font color="#ef4444" size="8"><b>■ HIGH</b></font>'
        '<font color="#64748b" size="7.5"> — blocks search visibility, fix first &nbsp;&nbsp;&nbsp;</font>'
        '<font color="#f59e0b" size="8"><b>■ MEDIUM</b></font>'
        '<font color="#64748b" size="7.5"> — hurts ranking, should be fixed &nbsp;&nbsp;&nbsp;</font>'
        '<font color="#10b981" size="8"><b>■ LOW</b></font>'
        '<font color="#64748b" size="7.5"> — minor, optional improvement</font>',
        _ps('SevLegend', fontSize=8, fontName='Helvetica', leading=12)))
    elements.append(Spacer(1, 12))
#SECTION 3 — Detailed Results
def _build_detailed_results(elements, test_cases, url):
    elements.append(_section_header('Detailed SEO Test Results', '#0d9488'))
    elements.append(Spacer(1, 4))
    elements.append(_p(
        '<font color="#64748b" size="7.5"><i>'
        'Real analysis results from Playwright (Chromium) + BeautifulSoup. '
        'Each row shows the check performed, its outcome, and the actual value found.'
        '</i></font>',
        _ps('DRInfo', fontSize=7.5, fontName='Helvetica', leading=10)))
    elements.append(Spacer(1, 8))

    hdr = [
        _p('<font color="#ffffff"><b>#</b></font>',
           _ps('DH0', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
        _p('<font color="#ffffff"><b>SEO Check</b></font>',
           _ps('DH1', fontSize=8, fontName='Helvetica-Bold')),
        _p('<font color="#ffffff"><b>Category</b></font>',
           _ps('DH2', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
        _p('<font color="#ffffff"><b>Status</b></font>',
           _ps('DH3', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
        _p('<font color="#ffffff"><b>Result / Detail</b></font>',
           _ps('DH4', fontSize=8, fontName='Helvetica-Bold')),
        _p('<font color="#ffffff"><b>Severity</b></font>',
           _ps('DH5', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
    ]
    rows = [hdr]
    row_styles = []

    SEV_COLORS = {'high': '#ef4444', 'medium': '#f59e0b', 'low': '#10b981'}

    for i, tc in enumerate(test_cases):
        status  = tc.get('status', 'fail')
        sc      = '#10b981' if status == 'pass' else '#ef4444'
        s_label = 'PASS' if status == 'pass' else 'FAIL'
        s_bg    = HexColor('#f0fdf4') if status == 'pass' else HexColor('#fef2f2')
        cat     = tc.get('category', 'technical')
        cc      = CAT_COLORS.get(cat, '#64748b')
        detail  = tc.get('detail', tc.get('suite', '—'))
        detail_short = detail[:75] + '…' if len(detail) > 75 else detail

        if tc['name'] in ('robots.txt Found', 'sitemap.xml Found'):
            parsed = urlparse(url)
            base = f'{parsed.scheme}://{parsed.netloc}'
            target = f'{base}/robots.txt' if tc['name'] == 'robots.txt Found' else f'{base}/sitemap.xml'
            detail_short = (
                f'{detail_short} — '
                f'<link href="{_esc(target)}" color="#3b82f6"><u>{_esc(target)}</u></link>'
            )

        ai      = tc.get('ai_analysis', {})
        sev     = ai.get('severity', 'medium')
        sevc    = SEV_COLORS.get(sev, '#f59e0b')

        rows.append([
            _p(f'<font color="#64748b"><b>{i+1}</b></font>',
               _ps(f'DID{i}', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
            _p(f'<b><font color="#1e293b" size="8">{tc["name"]}</font></b>',
               _ps(f'DN{i}', fontSize=8, fontName='Helvetica', leading=11)),
            _p(f'<font color="{cc}"><b>{cat.upper()}</b></font>',
               _ps(f'DC{i}', fontSize=7, fontName='Helvetica-Bold', alignment=TA_CENTER)),
            _p(f'<font color="{sc}"><b>{s_label}</b></font>',
               _ps(f'DS{i}', fontSize=7.5, fontName='Helvetica-Bold', alignment=TA_CENTER)),
            _p(f'<font color="#475569" size="7">{detail_short}</font>',
               _ps(f'DD{i}', fontSize=7, fontName='Helvetica', leading=10)),
            _p(f'<font color="{sevc}"><b>{sev.upper()}</b></font>',
               _ps(f'DSV{i}', fontSize=7, fontName='Helvetica-Bold', alignment=TA_CENTER)),
        ])
        row_styles.append(('BACKGROUND', (3, i+1), (3, i+1), s_bg))

    tbl = Table(rows, colWidths=[8*mm, 50*mm, 24*mm, 16*mm, 52*mm, 18*mm], repeatRows=1)
    tbl.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (-1,0), NAVY),
        ('ROWBACKGROUNDS',(0,1), (-1,-1), [WHITE, LIGHT_BG]),
        ('PADDING',       (0,0), (-1,-1), 7),
        ('LINEBELOW',     (0,0), (-1,-1), 0.4, BORDER),
        ('BOX',           (0,0), (-1,-1), 0.8, TEAL),
        ('VALIGN',        (0,0), (-1,-1), 'TOP'),
        ('ALIGN',         (0,0), (0,-1), 'CENTER'),
        ('ALIGN',         (2,0), (3,-1), 'CENTER'),
        ('ALIGN',         (5,0), (5,-1), 'CENTER'),
        ('LINEBEFORE',    (4,1), (4,-1), 1, BORDER),
    ] + row_styles))
    elements.append(tbl)
    elements.append(Spacer(1, 16))


# SECTION 4 — LLaMA Analysis per test
def _build_llama_analysis(elements, test_cases):
    elements.append(Spacer(1, 8))
    elements.append(_section_header('LLaMA Analysis — Root Cause & Fix per Check', INDIGO))
    elements.append(Spacer(1, 4))
    elements.append(_p(
        '<font color="#64748b" size="7.5"><i>'
        'AI-generated root cause and fix for each SEO check, '
        'based on the actual values detected on the page.'
        '</i></font>',
        _ps('LAInfo', fontSize=7.5, fontName='Helvetica', leading=10)))
    elements.append(Spacer(1, 8))

    SEV_COLORS = {'high': '#ef4444', 'medium': '#f59e0b', 'low': '#10b981'}
    SEV_BG     = {'high': HexColor('#fef2f2'), 'medium': HexColor('#fffbeb'), 'low': HexColor('#f0fdf4')}

    hdr = [
        _p('<font color="#ffffff"><b>#</b></font>',
           _ps('LAH0', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
        _p('<font color="#ffffff"><b>Check</b></font>',
           _ps('LAH1', fontSize=8, fontName='Helvetica-Bold')),
        _p('<font color="#ffffff"><b>Status</b></font>',
           _ps('LAH2', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
        _p('<font color="#ffffff"><b>Root Cause</b></font>',
           _ps('LAH3', fontSize=8, fontName='Helvetica-Bold')),
        _p('<font color="#ffffff"><b>Fix / Action</b></font>',
           _ps('LAH4', fontSize=8, fontName='Helvetica-Bold')),
        _p('<font color="#ffffff"><b>Sev.</b></font>',
           _ps('LAH5', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
    ]
    rows = [hdr]
    row_styles = []

    for i, tc in enumerate(test_cases):
        ai     = tc.get('ai_analysis', {})
        sev    = ai.get('severity', 'medium')
        sevc   = SEV_COLORS.get(sev, '#f59e0b')
        sevbg  = SEV_BG.get(sev, HexColor('#fffbeb'))
        status = tc.get('status', 'fail')
        sc     = '#10b981' if status == 'pass' else '#ef4444'
        sl     = 'PASS' if status == 'pass' else 'FAIL'

        rc    = _esc(ai.get('root_cause', '—'))
        fix   = _esc(ai.get('fix', '—'))
        rc_s  = rc[:70] + '…' if len(rc) > 70 else rc
        fix_s = fix[:70] + '…' if len(fix) > 70 else fix
        

        rows.append([
            _p(f'<font color="#64748b"><b>{i+1}</b></font>',
               _ps(f'LAID{i}', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
            _p(f'<b><font color="#1e293b" size="7.5">{tc["name"]}</font></b>',
               _ps(f'LAN{i}', fontSize=7.5, fontName='Helvetica', leading=10)),
            _p(f'<font color="{sc}"><b>{sl}</b></font>',
               _ps(f'LAS{i}', fontSize=7.5, fontName='Helvetica-Bold', alignment=TA_CENTER)),
            _p(f'<font color="#475569" size="7">{rc_s}</font>',
               _ps(f'LARC{i}', fontSize=7, fontName='Helvetica', leading=10)),
            _p(f'<font color="#4f46e5" size="7">{fix_s}</font>',
               _ps(f'LAF{i}', fontSize=7, fontName='Helvetica', leading=10)),
            _p(f'<font color="{sevc}"><b>{sev.upper()}</b></font>',
               _ps(f'LASV{i}', fontSize=6.5, fontName='Helvetica-Bold', alignment=TA_CENTER)),
        ])
        row_styles.append(('BACKGROUND', (0, i+1), (-1, i+1), sevbg))

    tbl = Table(rows, colWidths=[8*mm, 42*mm, 14*mm, 48*mm, 48*mm, 14*mm], repeatRows=1)
    tbl.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (-1,0), NAVY),
        ('PADDING',       (0,0), (-1,-1), 6),
        ('LINEBELOW',     (0,0), (-1,-1), 0.4, BORDER),
        ('BOX',           (0,0), (-1,-1), 0.8, INDIGO),
        ('VALIGN',        (0,0), (-1,-1), 'TOP'),
        ('ALIGN',         (0,0), (0,-1), 'CENTER'),
        ('ALIGN',         (2,0), (2,-1), 'CENTER'),
        ('ALIGN',         (5,0), (5,-1), 'CENTER'),
        ('LINEBEFORE',    (3,1), (3,-1), 1, BORDER),
        ('LINEBEFORE',    (4,1), (4,-1), 1, BORDER),
    ] + row_styles))
    elements.append(tbl)
    elements.append(Spacer(1, 16))


#SECTION 5 — AI Recommendations
def _build_ai_recommendations(elements, ai_result, seo_score, url):
    elements.append(Spacer(1, 8))
    elements.append(_section_header('AI Recommendations', INDIGO))
    elements.append(Spacer(1, 4))
    elements.append(_p(
        '<font color="#64748b" size="7.5"><i>'
        'Global SEO recommendations generated by LLaMA 3.3 — '
        'prioritized by impact on search rankings.'
        '</i></font>',
        _ps('AIInfo', fontSize=7.5, fontName='Helvetica', leading=10)))
    elements.append(Spacer(1, 10))

    # Summary block
    summary = ai_result.get('summary', '')
    if summary:
        summ_tbl = Table([[_p(
            f'<font color="#1e293b" size="8"><b>AI Summary: </b></font>'
            f'<font color="#475569" size="8">{summary}</font>',
            _ps('AISumm', fontSize=8, fontName='Helvetica', leading=12))
        ]], colWidths=[168*mm])
        summ_tbl.setStyle(TableStyle([
            ('BACKGROUND',    (0,0), (-1,-1), INDIGO_BG),
            ('BOX',           (0,0), (-1,-1), 1, INDIGO),
            ('LINEBEFORE',    (0,0), (0,-1),  3, INDIGO),
            ('LEFTPADDING',   (0,0), (-1,-1), 12),
            ('RIGHTPADDING',  (0,0), (-1,-1), 12),
            ('TOPPADDING',    (0,0), (-1,-1), 10),
            ('BOTTOMPADDING', (0,0), (-1,-1), 10),
        ]))
        elements.append(summ_tbl)
        elements.append(Spacer(1, 10))

    # Recommendations table
    recs = ai_result.get('recommendations', [])
    if recs:
        hdr = [
            _p('<font color="#ffffff"><b>Priority</b></font>',
               _ps('RH1', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
            _p('<font color="#ffffff"><b>Category</b></font>',
               _ps('RH2', fontSize=8, fontName='Helvetica-Bold', alignment=TA_CENTER)),
            _p('<font color="#ffffff"><b>Issue</b></font>',
               _ps('RH3', fontSize=8, fontName='Helvetica-Bold')),
            _p('<font color="#ffffff"><b>Fix</b></font>',
               _ps('RH4', fontSize=8, fontName='Helvetica-Bold')),
        ]
        rows = [hdr]
        row_styles = []

        PRI_BG = {
            'high':   HexColor('#fef2f2'),
            'medium': HexColor('#fffbeb'),
            'low':    HexColor('#f0fdf4'),
        }

        for i, rec in enumerate(recs):
            pri   = rec.get('priority', 'medium').lower()
            pc    = PRIORITY_COLORS.get(pri, '#f59e0b')
            pbg   = PRI_BG.get(pri, HexColor('#fffbeb'))
            cat   = rec.get('category', '—')
            issue = rec.get('issue', '—')
            fix   = rec.get('fix', '—')
            issue_s = issue[:65] + '…' if len(issue) > 65 else issue
            fix_s   = fix[:65]   + '…' if len(fix)   > 65 else fix

            rows.append([
                _p(f'<font color="{pc}"><b>{pri.upper()}</b></font>',
                   _ps(f'RP{i}', fontSize=7.5, fontName='Helvetica-Bold', alignment=TA_CENTER)),
                _p(f'<font color="#4f46e5"><b>{cat}</b></font>',
                   _ps(f'RC{i}', fontSize=7.5, fontName='Helvetica-Bold', alignment=TA_CENTER)),
                _p(f'<font color="#1e293b" size="7.5">{issue_s}</font>',
                   _ps(f'RI{i}', fontSize=7.5, fontName='Helvetica', leading=10)),
                _p(f'<font color="#475569" size="7.5">{fix_s}</font>',
                   _ps(f'RF{i}', fontSize=7.5, fontName='Helvetica', leading=10)),
            ])
            row_styles.append(('BACKGROUND', (0, i+1), (-1, i+1), pbg))

        tbl = Table(rows, colWidths=[20*mm, 28*mm, 60*mm, 60*mm], repeatRows=1)
        tbl.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), NAVY),
            ('PADDING',    (0,0), (-1,-1), 7),
            ('LINEBELOW',  (0,0), (-1,-1), 0.4, BORDER),
            ('BOX',        (0,0), (-1,-1), 0.8, INDIGO),
            ('VALIGN',     (0,0), (-1,-1), 'TOP'),
            ('ALIGN',      (0,0), (1,-1), 'CENTER'),
            ('LINEBEFORE', (2,1), (2,-1), 1, BORDER),
            ('LINEBEFORE', (3,1), (3,-1), 1, BORDER),
        ] + row_styles))
        elements.append(tbl)
        elements.append(Spacer(1, 10))

    # Action plan
    action_plan = ai_result.get('action_plan', [])
    if action_plan:
        elements.append(_p(
            '<font color="#1e293b" size="9"><b>Action Plan</b></font>',
            _ps('APH', fontSize=9, fontName='Helvetica-Bold', leading=12)))
        elements.append(Spacer(1, 6))
        for step in action_plan:
            step_tbl = Table([[_p(
                f'<font color="#4f46e5" size="7.5">{step}</font>',
                _ps('APStep', fontSize=7.5, fontName='Helvetica', leading=11))
            ]], colWidths=[168*mm])
            step_tbl.setStyle(TableStyle([
                ('BACKGROUND',    (0,0), (-1,-1), HexColor('#fafafa')),
                ('LEFTPADDING',   (0,0), (-1,-1), 16),
                ('TOPPADDING',    (0,0), (-1,-1), 5),
                ('BOTTOMPADDING', (0,0), (-1,-1), 5),
                ('LINEBELOW',     (0,0), (-1,-1), 0.3, BORDER),
                ('LINEBEFORE',    (0,0), (0,-1),  2, INDIGO),
            ]))
            elements.append(step_tbl)
        elements.append(Spacer(1, 16))


#SECTION 6 — Final Verdict
def _build_final_verdict(elements, summary, seo_score, test_cases):
    pass_count = summary.get('passed', 0)
    fail_count = summary.get('failed', 0)
    total      = summary.get('total', 17)
    pass_rate  = summary.get('pass_rate', 0)

    # Déterminer les catégories critiques échouées
    critical_failed = [
        tc for tc in test_cases
        if tc.get('status') == 'fail'
        and tc.get('category') in ('security', 'technical', 'meta')
    ]

    if critical_failed:
        vc, vb, vbrd = '#ef4444', HexColor('#fef2f2'), RED
        vi = '[FAIL]'
        cats = ', '.join(set(tc['category'].upper() for tc in critical_failed))
        vt = (f'SEO audit FAILED — critical issues detected in: {cats}. '
              f'These must be fixed to improve search engine visibility.')
    elif fail_count > 0:
        vc, vb, vbrd = '#b45309', HexColor('#fffbeb'), ORANGE
        vi = '[WARN]'
        vt = (f'SEO audit passed with {fail_count} non-critical issue(s). '
              f'Core technical SEO is functional but improvements are recommended.')
    else:
        vc, vb, vbrd = '#059669', HexColor('#f0fdf4'), GREEN
        vi = '[PASS]'
        vt = (f'SEO audit PASSED — all {pass_count} checks passed. '
              f'The page meets technical SEO best practices.')

    # Score color
    score_color = '#10b981' if seo_score >= 80 else '#f59e0b' if seo_score >= 50 else '#ef4444'

    elements.append(Spacer(1, 8))
    final_tbl = Table([[_p(
        f'<font color="{vc}" size="9"><b>{vi}  Final SEO Verdict</b></font><br/>'
        f'<font color="{vc}" size="8">{vt}</font><br/><br/>'
        f'<font color="#64748b" size="8"><b>SEO Score: </b></font>'
        f'<font color="{score_color}" size="8"><b>{seo_score}/100</b></font>'
        f'<font color="#94a3b8" size="8">    |    </font>'
        f'<font color="#64748b" size="8"><b>Pass Rate: </b></font>'
        f'<font color="{vc}" size="8"><b>{pass_rate}%</b></font>'
        f'<font color="#94a3b8" size="8">    |    </font>'
        f'<font color="#64748b" size="8"><b>Checks: </b></font>'
        f'<font color="#10b981" size="8"><b>{pass_count} passed</b></font>'
        f'<font color="#94a3b8" size="8"> / </font>'
        f'<font color="#ef4444" size="8"><b>{fail_count} failed</b></font>'
        f'<font color="#94a3b8" size="8"> / {total} total</font>',
        _ps('FV', fontSize=8, fontName='Helvetica', leading=13))
    ]], colWidths=[168*mm])
    final_tbl.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (-1,-1), vb),
        ('BOX',           (0,0), (-1,-1), 2, vbrd),
        ('LEFTPADDING',   (0,0), (-1,-1), 14),
        ('RIGHTPADDING',  (0,0), (-1,-1), 14),
        ('TOPPADDING',    (0,0), (-1,-1), 12),
        ('BOTTOMPADDING', (0,0), (-1,-1), 12),
    ]))
    elements.append(final_tbl)
    elements.append(Spacer(1, 20))


#SECTION 7 — Category Chart (PASS/FAIL par catégorie)
def _build_category_chart(elements, test_cases):
    elements.append(_section_header('Category Breakdown Chart', '#16a34a'))
    elements.append(Spacer(1, 8))

    cats = {}
    for tc in test_cases:
        cat = tc.get('category', 'technical')
        cats.setdefault(cat, {'pass': 0, 'fail': 0})
        if tc.get('status') == 'pass':
            cats[cat]['pass'] += 1
        else:
            cats[cat]['fail'] += 1

    categories = list(cats.keys())
    passed = [cats[c]['pass'] for c in categories]
    failed = [cats[c]['fail'] for c in categories]

    fig, ax = plt.subplots(figsize=(6.6, 3.0), dpi=150)
    x = range(len(categories))
    ax.bar(x, passed, color='#10b981', label='Passed')
    ax.bar(x, failed, bottom=passed, color='#ef4444', label='Failed')
    ax.set_xticks(list(x))
    ax.set_xticklabels([c.upper() for c in categories], rotation=40, ha='right', fontsize=7)
    ax.set_ylabel('Checks', fontsize=8)
    ax.tick_params(axis='y', labelsize=7)
    ax.legend(fontsize=7, loc='upper right', frameon=False)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    fig.tight_layout()

    img_buf = BytesIO()
    fig.savefig(img_buf, format='PNG', transparent=True)
    plt.close(fig)
    img_buf.seek(0)

    elements.append(Image(img_buf, width=160*mm, height=72*mm))
    elements.append(Spacer(1, 16))


#SECTION 8 — Environment & Execution Info
NEXTEST_VERSION = '1.0.0'  # ajuste si tu as une vraie version quelque part

def _build_environment_info(elements, execution_time=None):
    elements.append(_section_header('Environment & Execution Info', '#0d9488'))
    elements.append(Spacer(1, 8))
    exec_str = f'{execution_time:.2f}s' if execution_time else '—'

    def _env_card(label, value, accent):
        inner = Table([[
            _p(f'<font color="{accent}" size="7"><b>{label.upper()}</b></font>',
               _ps(f'EnvL{label}', fontSize=7, fontName='Helvetica-Bold', leading=9)),
        ], [
            _p(f'<font color="#1e293b" size="9.5"><b>{_esc(str(value))}</b></font>',
               _ps(f'EnvV{label}', fontSize=9.5, fontName='Helvetica-Bold', leading=12)),
        ]], colWidths=[78*mm])
        inner.setStyle(TableStyle([
            ('LEFTPADDING',   (0,0), (-1,-1), 10),
            ('RIGHTPADDING',  (0,0), (-1,-1), 10),
            ('TOPPADDING',    (0,0), (0,0), 8),
            ('BOTTOMPADDING', (0,0), (0,0), 2),
            ('TOPPADDING',    (0,1), (0,1), 0),
            ('BOTTOMPADDING', (0,1), (0,1), 8),
            ('LINEBEFORE',    (0,0), (0,-1), 2.5, HexColor(accent)),
            ('BACKGROUND',    (0,0), (-1,-1), LIGHT_BG),
            ('BOX',           (0,0), (-1,-1), 0.6, BORDER),
        ]))
        return inner

    items = [
        ('NexTest Version',  NEXTEST_VERSION,                              '#0d9488'),
        ('Python Version',   platform.python_version(),                   '#0d9488'),
        ('Analyzer Engine',  'Playwright (Chromium) + BeautifulSoup',     '#4f46e5'),
        ('Execution Time',   exec_str,                                    '#0d9488'),
    ]
    grid_rows = []
    row = []
    for i, (label, value, accent) in enumerate(items):
        row.append(_env_card(label, value, accent))
        if len(row) == 2:
            grid_rows.append(row)
            row = []
    if row:
        row.append('')
        grid_rows.append(row)

    grid = Table(grid_rows, colWidths=[84*mm, 84*mm])
    grid.setStyle(TableStyle([
        ('LEFTPADDING',  (0,0), (-1,-1), 0),
        ('RIGHTPADDING', (0,0), (-1,-1), 4),
        ('TOPPADDING',   (0,0), (-1,-1), 0),
        ('BOTTOMPADDING',(0,0), (-1,-1), 4),
        ('VALIGN',       (0,0), (-1,-1), 'TOP'),
    ]))
    elements.append(grid)
    elements.append(Spacer(1, 16))

#SECTION 9 — Methodology
def _build_methodology(elements):
    elements.append(_section_header('Audit Methodology', '#3b82f6'))
    elements.append(Spacer(1, 8))
    elements.append(_p(
        '<font color="#475569" size="8">'
        'This SEO audit performs 17 automated checks across 9 categories '
        '(Security, Accessibility, Meta, Structure, Mobile, Technical, Social, '
        'Content, Performance) by rendering the page in a headless Chromium '
        'browser (Playwright) and parsing the resulting DOM with BeautifulSoup, '
        'ensuring dynamically-loaded content (JS-rendered elements) is captured. '
        'Each check is evaluated against a fixed rule (tag presence, character '
        'length ranges, HTTP status codes) and enriched with a root-cause and fix '
        'recommendation generated by LLaMA 3.3, based on the actual values detected on the page.'
        '</font>',
        _ps('MethoTxt', fontSize=8, fontName='Helvetica', leading=13)))
    elements.append(Spacer(1, 16))




#SECTION 10 — Screenshot
def _build_executive_summary(elements, ai_result, seo_score, pass_count, fail_count, total):
    summary = ai_result.get("summary", "")
    recs = ai_result.get("recommendations", [])
    high_recs = [r for r in recs if r.get("priority", "").lower() == "high"][:3]
    if not summary and not high_recs:
        return

    elements.append(_section_header("Executive Summary", "#4f46e5"))
    elements.append(Spacer(1, 8))

    if not high_recs:
        elements.append(Spacer(1, 16))
        return

    elements.append(_p(
        '<font color="#1e293b" size="9"><b>Top Priority Actions</b></font>',
        _ps("ExecActionsTitle", fontSize=9, fontName="Helvetica-Bold")))
    elements.append(Spacer(1, 8))

    for i, rec in enumerate(high_recs, 1):
        issue = _esc(rec.get("issue", ""))
        fix = _esc(rec.get("fix", ""))
        cat = _esc(rec.get("category", "—"))

        card = Table([[
            _p(f'<font color="#ffffff" size="11"><b>{i}</b></font>',
               _ps(f'ExecNum{i}', fontSize=11, fontName='Helvetica-Bold', alignment=TA_CENTER)),
            _p(
                f'<font color="#ef4444" size="7"><b>{cat.upper()}</b></font><br/>'
                f'<font color="#1e293b" size="9"><b>{issue}</b></font><br/>'
                f'<font color="#64748b" size="8">{fix}</font>',
                _ps(f'ExecBody{i}', fontSize=9, fontName='Helvetica', leading=13)),
        ]], colWidths=[12*mm, 156*mm])
        card.setStyle(TableStyle([
            ('BACKGROUND',    (0,0), (0,-1), RED),
            ('BACKGROUND',    (1,0), (1,-1), HexColor('#fef2f2')),
            ('VALIGN',        (0,0), (-1,-1), 'MIDDLE'),
            ('ALIGN',         (0,0), (0,-1), 'CENTER'),
            ('LEFTPADDING',   (1,0), (1,-1), 12),
            ('RIGHTPADDING',  (1,0), (1,-1), 12),
            ('TOPPADDING',    (0,0), (-1,-1), 10),
            ('BOTTOMPADDING', (0,0), (-1,-1), 10),
            ('BOX',           (0,0), (-1,-1), 0.8, HexColor('#fecaca')),
        ]))
        elements.append(card)
        elements.append(Spacer(1, 6))

    elements.append(Spacer(1, 16))
    
def _build_screenshot(elements, screenshot_bytes, url):
    if not screenshot_bytes:
        return

    try:
        pil_img = PILImage.open(BytesIO(screenshot_bytes))
        iw, ih = pil_img.size
    except Exception as e:
        print(f"[SEO PDF] Could not open screenshot image: {e}")
        return

    max_w, max_h = 160*mm, 190*mm
    img_w, img_h = max_w, ih * (max_w / iw)
    if img_h > max_h:
        img_w, img_h = img_w * (max_h / img_h), max_h

    block = [
        _section_header('Page Screenshot', '#16a34a'),
        Spacer(1, 8),
        _p(
            f'<font color="#64748b" size="7.5"><i>Visual snapshot of {_esc(url)} at analysis time.</i></font>',
            _ps('ScreenInfo', fontSize=7.5, fontName='Helvetica', leading=10)),
        Spacer(1, 8),
        Image(BytesIO(screenshot_bytes), width=img_w, height=img_h),
        Spacer(1, 16),
    ]
    elements.append(KeepTogether(block))

#MAIN
def generate_seo_pdf(generation_data: dict) -> bytes:
    buffer = BytesIO()

    url        = generation_data.get('url', '')
    seo_score  = generation_data.get('seo_score', 0)
    summary    = generation_data.get('summary', {})
    test_cases = generation_data.get('test_cases', [])
    ai_result  = generation_data.get('ai', {})
    # 'screenshot' arrives as a base64 string when it traveled through the
    # /generate-seo → frontend → /generate-pdf JSON round trip, but may also
    # be raw bytes if generate_seo_pdf is ever called in-process.
    screenshot_bytes = _decode_screenshot(generation_data.get('screenshot'))
    execution_time   = generation_data.get('execution_time')   # secondes (float) ou None

    pass_count = summary.get('passed', 0)
    fail_count = summary.get('failed', 0)
    total      = summary.get('total', len(test_cases))
    pass_rate  = summary.get('pass_rate', 0)
    rate_color = '#10b981' if pass_rate >= 80 else '#f59e0b' if pass_rate >= 50 else '#ef4444'
    score_color = '#10b981' if seo_score >= 80 else '#f59e0b' if seo_score >= 50 else '#ef4444'

    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        rightMargin=20*mm, leftMargin=22*mm,
        topMargin=58*mm, bottomMargin=20*mm,
    )

    elements = []

    #HEADER
    header_data = [[
        _p('<font color="#16a34a"><b>NEX</b></font><font color="#ffffff">TEST</font>',
           _ps('SLogo', fontSize=24, fontName='Helvetica-Bold')),
        _p(f'<font color="#64748b">Generated</font><br/>'
           f'<font color="#94a3b8">{datetime.now().strftime("%B %d, %Y  •  %H:%M")}</font>',
           _ps('SDate', fontSize=8.5, fontName='Helvetica',
               alignment=TA_RIGHT, leading=13)),
    ]]
    header_tbl = Table(header_data, colWidths=[90*mm, 78*mm])
    header_tbl.setStyle(TableStyle([
        ('VALIGN',        (0,0), (-1,-1), 'MIDDLE'),
        ('TOPPADDING',    (0,0), (-1,-1), 0),
        ('BOTTOMPADDING', (0,0), (-1,-1), 0),
    ]))
    elements.append(Spacer(1, -38*mm))
    elements.append(header_tbl)
    elements.append(Spacer(1, 6*mm))
    elements.append(_p('SEO Test Report',
        _ps('Title', fontSize=22, textColor=WHITE,
            fontName='Helvetica-Bold', spaceAfter=2)))
    elements.append(Spacer(1, 14*mm))

    #INFO BOX
    def il(txt):
        return _p(f'<font color="#64748b">{txt}</font>',
                  _ps(f'IL{txt}', fontSize=8, fontName='Helvetica-Bold', leading=12))
    def iv(txt):
        return _p(f'<font color="#1e293b">{txt}</font>',
                  _ps(f'IV{txt}', fontSize=8.5, fontName='Helvetica', leading=12))

    exec_row_val = f'{execution_time:.2f}s' if execution_time else '—'
    info_tbl = Table([
        [il('URL'),        iv(url)],
        [il('Analyzer'),   _p('<font color="#16a34a"><b>Playwright (Chromium) + BeautifulSoup</b></font>',
                              _ps('IVSEO', fontSize=8.5, fontName='Helvetica', leading=12))],
        [il('Test Type'),  _p('<font color="#16a34a"><b>SEO Audit — 17 Checks</b></font>',
                              _ps('IVTT', fontSize=8.5, fontName='Helvetica', leading=12))],
        [il('SEO Score'),  _p(f'<font color="{score_color}"><b>{seo_score}/100</b></font>',
                              _ps('IVSC', fontSize=8.5, fontName='Helvetica', leading=12))],
        [il('Execution Time'), iv(exec_row_val)],
        [il('Generated'),  iv(datetime.now().strftime('%Y-%m-%d  %H:%M'))],
    ], colWidths=[32*mm, 136*mm])
    info_tbl.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (0,-1), LIGHT_BG),
        ('PADDING',       (0,0), (-1,-1), 7),
        ('LINEBELOW',     (0,0), (-1,-2), 0.4, BORDER),
        ('BOX',           (0,0), (-1,-1), 0.8, BORDER_DARK),
        ('ROWBACKGROUNDS',(0,0), (-1,-1), [WHITE, LIGHT_BG]),
        ('LEFTPADDING',   (0,0), (0,-1), 10),
        ('VALIGN',        (0,0), (-1,-1), 'MIDDLE'),
    ]))
    elements.append(info_tbl)
    elements.append(Spacer(1, 20))

    #STAT CARDS
    stats_data = [[
        _stat_card(pass_count,       'PASSED',    '#10b981', GREEN_BG),
        _stat_card(fail_count,       'FAILED',    '#ef4444', RED_BG),
        _stat_card(f'{pass_rate}%',  'PASS RATE', rate_color,
                   GREEN_BG if pass_rate >= 80 else ORANGE_BG if pass_rate >= 50 else RED_BG),
        _stat_card(f'{seo_score}',   'SEO SCORE', score_color,
                   GREEN_BG if seo_score >= 80 else ORANGE_BG if seo_score >= 50 else RED_BG),
        _stat_card(total,            'TOTAL',     '#3b82f6', BLUE_BG),
    ]]
    outer = Table(stats_data, colWidths=[33.6*mm]*5)
    outer.setStyle(TableStyle([
        ('ALIGN',  (0,0), (-1,-1), 'CENTER'),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('PADDING',(0,0), (-1,-1), 2),
    ]))
    elements.append(outer)
    elements.append(Spacer(1, 20))

    # ALL SECTIONS
   
    # ALL SECTIONS
    _build_screenshot(elements, screenshot_bytes, url)
    _build_methodology(elements)
    _build_seo_scenarios(elements, test_cases, url)
    _build_category_summary(elements, test_cases)
    _build_severity_legend(elements)
    _build_category_chart(elements, test_cases)
    _build_detailed_results(elements, test_cases, url)
    _build_llama_analysis(elements, test_cases)
    _build_ai_recommendations(elements, ai_result, seo_score, url)
    _build_environment_info(elements, execution_time)
    _build_final_verdict(elements, summary, seo_score, test_cases)
    _build_executive_summary(elements, ai_result, seo_score, pass_count, fail_count, total)

    doc.build(elements, onFirstPage=on_page_seo, onLaterPages=on_page_seo)
    return buffer.getvalue()

#SECTION XLSX — Excel version (same data, same color language as the PDF)
_XLSX_FONT = "Calibri"
_XLSX_THIN = Side(style="thin", color="E2E8F0")
_XLSX_BORDER = Border(left=_XLSX_THIN, right=_XLSX_THIN, top=_XLSX_THIN, bottom=_XLSX_THIN)


def _xlsx_header_row(ws, row, headers, col_start=1):
    for i, h in enumerate(headers, start=col_start):
        c = ws.cell(row=row, column=i, value=h)
        c.font = Font(name=_XLSX_FONT, bold=True, color="FFFFFF", size=10)
        c.fill = PatternFill("solid", fgColor="0A0F1E")
        c.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        c.border = _XLSX_BORDER


def _xlsx_autofit(ws, widths):
    for i, w in enumerate(widths, start=1):
        ws.column_dimensions[get_column_letter(i)].width = w


